### ISSUE TITLE
Connect call failed

### ISSUE THREAD

**Issue by jproffitt** [django/channels_redis#102]
My apologies if this is just a problem with my system and not a bug in this project, but I recently upgraded to channels 2 / channels_redis 2, and all of a sudden I get this error regularly:

	OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379), [Errno 111] Connect call failed ('127.0.0.1', 6379)
	  File "asgiref/sync.py", line 64, in __call__
		return call_result.result()
	  File "concurrent/futures/_base.py", line 398, in result
		return self.__get_result()
	  File "concurrent/futures/_base.py", line 357, in __get_result
		raise self._exception
	  File "asgiref/sync.py", line 78, in main_wrap
		result = await self.awaitable(*args, **kwargs)
	  File "channels_redis/core.py", line 322, in group_send
		await self.send(channel, message)
	  File "channels_redis/core.py", line 132, in send
		async with self.connection(index) as connection:
	  File "channels_redis/core.py", line 399, in __aenter__
		self.conn = await aioredis.create_redis(**self.kwargs)
	  File "aioredis/commands/__init__.py", line 174, in create_redis
		loop=loop)
	  File "aioredis/connection.py", line 107, in create_connection
		timeout, loop=loop)
	  File "asyncio/tasks.py", line 339, in wait_for
		return (yield from fut)
	  File "aioredis/stream.py", line 19, in open_connection
		lambda: protocol, host, port, **kwds)
	  File "asyncio/base_events.py", line 786, in create_connection
		', '.join(str(exc) for exc in exceptions)))

It happens when I try to send a message to a group in a django view like:

    AsyncToSync(channel_layer.group_send)("group_name",
        {"type": "status_update", "text": json_data}
    )

It only happens sometimes. Most of the time it works fine, but I consistently see this error happen randomly. Redis server is up and running just fine. I never saw anything like this happen before I upgraded to channels 2.

Is there possibly something I have done wrong, or could there be something wrong here? Thanks for the awesome work BTW!

```
asgiref==2.3.0
channels==2.1.0
channels_redis==2.1.1
```

**Comment by andrewgodwin** [comment]
It looks like a pretty standard networking error from the Redis library - we changed underlying Redis library from 1 to 2 so it's possible the new one is more sensitive to bad network configurations where the old one retried.

There's nothing we can do in Channels about this - that error is coming from your underlying OS. I would check to see if you have any symptoms of socket exhaustion when this is happening?

**Comment by minhTNH** [comment]
For those get this error, try to run Redis server.
https://redis.io/topics/quickstart

**Comment by DubeySuvodeep** [comment]
docker inspect --format '{{ .NetworkSettings.IPAddress }}' <container_name>
o/p : <conatiner_ip>
Use the IP address in django settings:

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(<conatiner_ip>, 6379)],
        },
    },
}

**Comment by jai8004** [comment]
> For those get this error, try to run Redis server.
> https://redis.io/topics/quickstart

it worked just install redis and start the server

**Comment by enjoysmath** [comment]
I'm getting `[Errno 111] Connect call failed ('::1', 8000,`  spuriously like this as well.  Things were connecting yesterday, and now this.  

I'm doing MainApp (Python) <-{WebSocket}-> A ChannelsConsumer subclass (Django).

Any ideas?  Yes, I've started redis.  `sudo service redis-server start`
