### ISSUE TITLE
2.2 makes breaking call to layers.get_capacity

### ISSUE THREAD

**Issue by robdoesstuff** [django/channels_redis#105]
Running Channels 2.1.1, Channels_Redis 2.2.0 just sending a group message:

site-packages/channels_redis/core.py" in _map_channel_to_connection
  367.             channel_to_capacity[channel] = self.get_capacity(message)

site-packages/channels/layers.py" in get_capacity
  127.             if pattern.match(channel):

Exception Type: TypeError
Exception Value: expected string or bytes-like object

It appears as though the calling function is passing the message (a dict) to get_capacity, which is expecting a string to pattern-match against.

**Comment by andrewgodwin** [comment]
Looks like it only failed if you set `channel_capacity` as a setting. The tests catch this now, and I'll roll a release.
