### ISSUE TITLE
Release new version of package on PIP

### ISSUE THREAD

**Issue by TheBuky** [django/channels_redis#108]
Makes it possible to realse the last version of the package on PIP ?

> Could not find a version that satisfies the requirement asgi-redis==2.2.1 (from versions: 0.8, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.9.1, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3)
> No matching distribution found for asgi-redis==2.2.1

Thank

**Comment by andrewgodwin** [comment]
The Channels 2 version of the package is called `channels_redis`, as it is incompatible with the previous one.

**Comment by TheBuky** [comment]
Thank for replying. Why don't I find any information about this?
And when I update Channels to Channels 2, all dependencies are broken...

**Comment by andrewgodwin** [comment]
There's a lot of information about it and upgrading in the docs: http://channels.readthedocs.io/en/latest/one-to-two.html
