### ISSUE TITLE
CPU usage goes down randomly and client received the message turn to be slow 

### ISSUE THREAD

**Issue by PoloPing** [django/channels_redis#112]
Due to I have a production on Azure and I found out the the client got message really slow sometime.
so I tried to do some load test. 

at first, I thought it my code problem, so I decide to use the simple code to test again and I found out it also happen as I used the simple code.

there is the simple code 

`
  class ChatConsumer(AsyncJsonWebsocketConsumer):

    async def connect(self):
        self.rooms = set()
        await self.accept()

    async def receive_json(self, content):
        command = content.get('command', None)
        try:
            if command == 'join':
                await self.join_room(content.get('receivers'))
            elif command == 'live':
                await self.record_live_user(content)
            elif command == 'send':
                await self.send_room(content)
            elif command == 'leave':
                await self.leave_room(content.get('receivers'))
            else:
                raise ClientError(msg='wrong command', error_type=0)
        except ClientError as e:
            e.send_to(self.scope['user'], self)

    async def disconnect(self, code):
        for room_id in list(self.rooms):
            try:
                await self.channel_layer.group_discard(
                    f"room-{room_id}",
                    self.channel_name
                )
            except ClientError:
                pass

    async def join_room(self, receivers):
        for r in receivers:
            self.rooms.add(r)
            await self.channel_layer.group_add(
                f"room-{r}",
                self.channel_name
            )

    async def send_room(self, message):
        msg = {'user': self.scope['user']}
        msg.update(message.items())

        for r in message['receivers']:
            await self.channel_layer.group_send(
                f"room-{r}",
                {
                    'type': 'chat_message',
                    'message': msg
                }
            )

    async def chat_message(self, event):
        await self.send_json(event["message"])

    async def encode_json(cls, content):
        return dumps(content)
`
and this is Response from web socket per second 

<img width="1175" alt="2018-07-04 11 10 40" src="https://user-images.githubusercontent.com/4884520/42254820-334a42ba-7f7b-11e8-8fe2-00979070df63.png">

and this is CPU Usage 

<img width="103" alt="2018-07-04 11 14 05" src="https://user-images.githubusercontent.com/4884520/42255184-1dc0ea3c-7f7d-11e8-943d-6f903bc35d40.png">

and my requiremetns

daphne==2.1.0
Django==1.11.4
channels==2.1.0
channels-redis==2.1.1

it's kind of similar like issue #81 I think

<new found out, redis log showed lesser when load test run for a while>
<there is redis log>
[redis.log.zip](https://github.com/django/channels_redis/files/2162778/redis.log.zip)

**Comment by PoloPing** [comment]
I forked the channels-redis and found out that if there are too many messages,
the receive function can't get processing from CPU due to send function and receive_loop_task...

**Comment by andrewgodwin** [comment]
Did you try running more servers to spread the load around? `channels-redis` isn't built to be amazingly efficient in a single process yet.

**Comment by PoloPing** [comment]
@andrewgodwin , I have tried to deploy 2 or 3 node to make test load, 
all of results of charts are similar and I found out in channels-redis, it seems didn't separate
send task and receive task to different event loop.
receive task will be as same as users, but the send tasks depends on Request Per second so that 
if send tasks increase too quickly, it seems block the event-loop.

**Comment by andrewgodwin** [comment]
You can't have two event loops in asyncio, it's built around a single event loop. I don't think there's a specific bug we can solve here - it's not going to be able to handle infinite traffic, and we have some people working on making both sending and receiving more efficient, so it will improve over time.

Since there's not a specific thing here we can solve, just ongoing efficiency improvements, I am going to close this. Making the channel layer perform well depends entirely on your setup, or you are free to replace it with one of your own design.

**Comment by Dean-Christian-Armada** [comment]
Hi Andrew,

I'm Polo's co-engineer. Can you be more specific in the part of "channel layer perform well depends entirely on your setup".? We really need assistance for improving our performance.. So far our setup is:

```
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core'
        '.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(REDIS_HOST, 6379)],
            "capacity": os.environ.get('channel_layer_capacity', 100000)
        },
    },
}
```

Also I found it very weird that adding 2 more servers load-balanced by nginx did not really improve our performance.. Is it possible that we just did something wrong?

**Comment by andrewgodwin** [comment]
What I mean is that having your application perform well is a combination of:
* How many Daphne instances you are running (you tried this it sounds like)
* How powerful the Redis server you're running is
* How many Redis servers you have given channels_redis (it can shard across multiple)
* How well your network performs

If you scaled the number of Daphne servers and it's still slow, then it's likely you're saturating the Redis server. If it's not that, then you probably have a sending pattern than is making channels_redis do a lot of packing and unpacking of messages, and it's probably not suitable for that, so you'd need to find a different cross-process communication solution or change how you're calling it.
