### ISSUE TITLE
Version of  asgi-redis  incompatible with version  asgiref

### ISSUE THREAD

**Issue by FrankLiu007** [django/channels_redis#113]
After install   channels_redis  using pip3, I got asgi-redis 1.4.3 has requirement asgiref~=1.1.2, but you'll have asgiref 2.3.2 which is incompatible. This may be misleading,  as verything  goes fine except that warning.

**Comment by andrewgodwin** [comment]
`asgi-redis` is an outdated package (the previous version of `channels_redis`). You can uninstall it to solve this error.
