### ISSUE TITLE
Issue in group_send in consumers.py file in channel_redis

### ISSUE THREAD

**Issue by rupamhazra** [django/channels_redis#115]
I have stuck to this issue await connection.eval(group_send_lua, keys=channel_redis_keys, args=args)
  ERR unknown command 'EVAL'.

Please help me out

**Comment by andrewgodwin** [comment]
I suspect it means you have a very old version of Redis, or it's otherwise limited in some way (e.g. you can't use `redis-cluster`). Not a Channels problem I'm afraid - you need a redis that responds to the `EVAL` command!

**Comment by Emizy** [comment]
kindly specify the version please
