### ISSUE TITLE
issue on installing mysqlclient on python

### ISSUE THREAD

**Issue by rupamhazra** [django/channels_redis#116]
this error occurred  "error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2".

Please help me out

**Comment by andrewgodwin** [comment]
I'm afraid I can't help with individual Windows issues - you'll need to go to the support channels for the thing that's failing (like mysqlclient). Sorry.
