### ISSUE TITLE
Configuring CHANNEL_LAYERS using hosts dicts

### ISSUE THREAD

**Issue by byrman** [django/channels_redis#119]
According to the [docs](https://github.com/django/channels_redis#hosts), you have several options to specify hosts when configuring CHANNEL_LAYERS:

* URIs
* (host, port) tuples
* dicts conforming to [create_connection](https://aioredis.readthedocs.io/en/v1.1.0/api_reference.html#aioredis.create_connection)

It's the 3rd option (dicts) I'm interested in, but I keep getting a "tuple or str expected" assertion error in aioredis. Is it possible to provide an example in the docs on the correct usage of the dicts option?

**Comment by andrewgodwin** [comment]
What it means is that you should supply dictionaries that match the keyword arguments for `create_connection` - i.e. ones you could pass with `**kwargs`.

**Comment by byrman** [comment]
Thanks for your time. Could it be that this option doesn't work (anymore)?

**Comment by andrewgodwin** [comment]
I checked in the code yesterday and it still appears to be there. If you can make a counterexample that doesn't work when passed in I can check that looks alright.

**Comment by byrman** [comment]
The docs gave me the impression that I had to provide a *list* of dicts:

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [{
                "address": (REDIS_HOST, REDIS_PORT),
                "db": REDIS_DB,
            }],
        },
    },
}
```

But I misunderstood. This works out alright:

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": {
                (REDIS_HOST, REDIS_PORT): {"db": REDIS_DB},
            },
        },
    },
}
```

Thanks for your help, Andrew.

**Comment by andrewgodwin** [comment]
Hmmm it is actually meant to be a list of dicts!

**Comment by andrewgodwin** [comment]
(e.g. the default value is `[{"address": ("localhost", 6379)}]`)

**Comment by andrewgodwin** [comment]
I just configured my settings like this:

```
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [
                    {
                        "address": ("localhost", 6379),
                        "db": 0,
                    }
                ],
            },
        },
    }
```

and it works, as expected. Are you sure you have the right versions of all the packages involved here?

**Comment by byrman** [comment]
Thanks for checking. It must be something with my setup then. I'll dig further and report back here if I find something. In the meantime I will switch to URIs (option 1), which is another way of passing db numbers and works for me too.
