### ISSUE TITLE
Why is the default channel capacity only 100

### ISSUE THREAD

**Issue by ostcar** [django/channels_redis#121]
I have a test scenario where 20 clients are connected via websockets. 10 send a message at the same time which are is redirected to all clients. So there are 200 messages that have to be send. But I can receive only some more then 100. When I set a higher channel capacity, every thing works fine.

So me question is: Is there a reason why the default channel capacity is only 100?

In the redis documentation it says:
> The max length of a list is 232 - 1 elements (4294967295, more than 4 billion of elements per list).
> 
> The main features of Redis Lists from the point of view of time complexity are the support for constant time insertion and deletion of elements near the head and tail, even with many millions of inserted items. Accessing elements is very fast near the extremes of the list but is slow if you try accessing the middle of a very big list, as it is an O(N) operation.

https://redis.io/topics/data-types

channels_redis calls only calls `rpush` and `blpop`. When I understand the redis documentation correctly, then they should work in constant time even when the list has thousands of elements.

I am using channel_redis 2.2.1. #107 is not released jet. Maybe my initial problem will be solved when this pr is released. But the questions stays if the channel capacity on redis could be set (per default) to something like 100,000.

**Comment by andrewgodwin** [comment]
It's mostly because that's a reasonable size for small installations - the capacity is a buffer size, so a smaller one shows up problems with mismatched producer vs. consumer speeds earlier. It's presumed you'd change it in a bigger production environment.
