### ISSUE TITLE
bug: channel layer don't close clients when oppened from celery task since 2.3

### ISSUE THREAD

**Issue by Christophe31** [django/channels_redis#124]
Since 2.3, I have redis having too much connections from celery workers, I suppose it may be linked with this pull request: https://github.com/django/channels_redis/pull/117 .

Every notification open a client which don't close.

Everytime I send a message from a task, I get my channel_layer. I don't close it manualy, but once it run a while (3 days with my load), I have too much clients conected on redis (>10000).

The channels documentation don't ask to close the layers manually, and celery tasks (to my knowledge) don't expect persistance of anything from a task to an other.

```
channel_layer = get_channel_layer()
async_to_sync(channel_layer.group_send)(channel, {
    "type": "send.message",
    "message": str(message)})
```

I tested back with 2.2.1, the issue disapeared.

**Comment by andrewgodwin** [comment]
Hi, I'm afraid that I can't solve a bug like this without either explicit steps to reproduce on a fresh example project - we need to make sure it's not a side-effect of your application (see https://channels.readthedocs.io/en/latest/support.html for more)

Until then, I'm going to close this - please reopen with the example project and steps to reproduce if you can.

**Comment by Christophe31** [comment]
As I have a quick fix (using old version), I'm not in a hurry to find a fix, and isolating from my project a minimal one which reproduce the bug seems like a lot of work, I understand it should not be yours to do, if I'm the only one which have issue with the sample code run from a celery task, I suppose you are right… As the release was still fearly new, I thought it was an issue with celery tasks which keep but don't close redis client. As 10 000 notification tasks don't seems like a lot, I suppose you would have more issues if it was the case. Thx for feedback I'll see if I can find myself time to isolate the root of the issue.

**Comment by tiltec** [comment]
I seem to have a similar problem and I tracked it down to the combination of `async_to_sync` and the new `ConnectionPool` of channels_redis. I'm working on a minimal repro now.
