### ISSUE TITLE
Redis connections keep increasing when used with async_to_sync

### ISSUE THREAD

**Issue by tiltec** [django/channels_redis#125]
I noticed that our task runner (huey) was keeping over 1000 connections to Redis open. After a day of digging around, I noticed that it can also happen in a plain Django Channels environment.

Here's a simple repro using django management commands:

https://github.com/tiltec/channels-redis-sync-repro/

It shows that sending with `async_to_sync` opens a new redis connection per message and never closes it again.

This is a regression from channels_redis 2.2.1.

### Related issues:
- https://github.com/django/channels_redis/issues/124
- https://github.com/django/channels_redis/issues/122

**Comment by philipbelesky** [comment]
We've noticed what appears to be a similar problem. Users generally run our app on a Heroku environment with a highly constrained redis resource (30 max connections) although we only use channel layers / `async_to_sync` on a small number of pages. Since the upgrade we've noticed a lot `ERR max number of clients reached` being reported.

**Comment by prokher** [comment]
JFYI. We saw a similar issue some time ago. It seemed that the reason is that `async_to_sync` constructs new event loop for each call. (Well, if it is called from the thread other than the one created by `sync_to_async`.)

**Comment by ruralscenery** [comment]
in function sync_to_async after following codes:

    if hasattr(loop, "shutdown_asyncgens"):
        loop.run_until_complete(loop.shutdown_asyncgens()) 

append following line, would be closed connection properly:
    
    loop.run_until_complete(get_channel_layer().close_pools())

**Comment by michael-k** [comment]
The PR that introduced connection pooling is: django/channels_redis#117

@jberci in the PR you mention

> we (…) haven't seen any problems internally that could be attributed to this in a while

I wonder why you did not run into this.  Do you never send messages from sync code?

**Comment by m3nu** [comment]
Ran into this as well. Adding the line as described by @ruralscenery fixed it. In `asgiref/sync.py:50`

**Comment by andrewgodwin** [comment]
Unfortunately we can't add that line into `asgiref` as it's specific to the channel layer. This problem needs to be solved in the Redis layer, and if not I'll have to roll back the connection pooling PR and revert to a pre-pooling world (I don't have the time to trace down what's going on in there).

In the meantime, if this affects you, please use version 2.2.1.

**Comment by ruralscenery** [comment]
@michael-k when you use channels 2 to send the message out of django box, for example, using celery task to send message by the channel_layer.send function, every call of channel_layer.send will create a new connection and new asyncio event loop, the new event loop code in asgiref/sync async_to_sync function close the event loop but redis connection, so it leaves the redis connection still alive there.

**Comment by adihat** [comment]
@andrewgodwin using channels-redis v2.2.1 certainly does solve this issue. Infact it makes the experience a lot better.
I hit the async_to_sync() repetedly using a loop and it updated the UI smoothly. Any reason this experience isn't seen in 2.3?

**Comment by onekiloparsec** [comment]
This fix has a drast impact on the number of connections used in a django app deployed on heroku, thanks a lot:
<img width="584" alt="Screenshot 2019-07-07 at 22 12 07" src="https://user-images.githubusercontent.com/226224/60825898-02ce4f00-a1ad-11e9-8e2b-0395294a117e.png">
