### ISSUE TITLE
group_send eats messages with single subscriber, works as expected with 2.

### ISSUE THREAD

**Issue by einsweniger** [django/channels_redis#131]
This might be related to #86.

I've "abused" the chat (from the tutorial), to function as a search box.
When a user submits text, I query the backend and send back several json objects for the result.

When there are 2 subscribers connected to the `AsyncWebsocketConsumer`/`ChatConsumer` everything works as expected.
When I'm sending it back through `self.send` it works as well.

With only one subscriber connected to the chat, everything works until I'm sending more than 101 messages via `self.channel_layer.group_send`:
```
    async def receive(self, text_data):
        text_data_json = json.loads(text_data)
        message = text_data_json['message']

        for i in range(101):
            await self.channel_layer.group_send(
                self.room_group_name,
                {
                    'type': 'chat_message',
                    'message': str(i)
                }
            )

        # This will run, but it's not received
        await self.channel_layer.group_send(
            self.room_group_name,
            {
                'type': 'chat_message',
                'message': message
            }
        )
```
([A gist for completeness](https://gist.github.com/einsweniger/6e131407ab562180f90ff1d5595e9b9e#file-consumers-py-L29))

In this example, all 101 messages {0..100} are delivered, the last message with the user-sent content is not.
If you increased to `range(102)` or more, the integer responses will also drop silently.
There are no errors in the redis log, and channels_redis also falls silent.

Just to reiterate: as soon as another websocket connection opens, it all behaves like expected (until it's closed, then everything is borked again).

> Please also try and include, if you can:

> - Your OS and runtime environment, and browser if applicable

- `Linux 4.18.9-arch1-1-ARCH #1 SMP PREEMPT Wed Sep 19 21:19:17 UTC 2018 x86_64 GNU/Linux`
- Bug appears in both, firefox-developer-edition and google-chrome stable
- redis 4.0.11

> - A `pip freeze` output showing your package versions
```
aioredis==1.1.0
asgiref==2.3.2
async-timeout==3.0.0
attrs==18.2.0
autobahn==18.9.2
Automat==0.7.0
channels==2.1.3
channels-redis==2.3.0
constantly==15.1.0
daphne==2.2.2
Django==2.1.1
hiredis==0.2.0
hyperlink==18.0.0
idna==2.7
incremental==17.5.0
msgpack==0.5.6
PyHamcrest==1.9.0
pytz==2018.5
six==1.11.0
Twisted==18.7.0
txaio==18.8.1
zope.interface==4.5.0
```
> - How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)

through runserver

> - Console logs and full tracebacks of any errors

N/A

**Comment by einsweniger** [comment]
Addendum: I've just noticed that there's a capacity (set to 100 by default) which might play into this, so this is my own fault, I guess. I'll still keep this active, since it works for multiple subscribers? Not sure if this is intended.

**Comment by andrewgodwin** [comment]
Are you saying it doesn't work for one subscriber with one message, or that it doesn't work for one subscriber with 101 messages?

**Comment by andrewgodwin** [comment]
Does it work for one subscriber and 1 message?

**Comment by einsweniger** [comment]
yes. it does.

**Comment by andrewgodwin** [comment]
Then it is working as expected - the bug is that it works with two subscribers and 101 messages, honestly. Unless you can outline a clear case where you think it should work (while not exceeding the channel limit, which is what you're hitting at 100) where it currently does not, I am going to have to close this.

**Comment by andrewgodwin** [comment]
It is meant to be enforced as best as possible, but sometimes it's not perfect.
