### ISSUE TITLE
redis 3.0.1 incompatible with asgi_redis==1.4.3

### ISSUE THREAD

**Issue by amir-hadi** [django/channels_redis#138]
A new release of the Python redis library (version 3.0.1) is incompatible with asgi_redis==1.4.3, because of breaking changes for MSET, MSETNX and ZADD. See the release description at https://pypi.org/project/redis/3.0.1/

A workaround is to fix the used redis library version at `redis==2.10.6`

**Comment by andrewgodwin** [comment]
Unfortunately `asgi_redis` is no longer maintained as it's for channels 1.x; this is now the repo for `channels_redis`. Sorry!
