### ISSUE TITLE
how can i auth redis with a special symbol in password

### ISSUE THREAD

**Issue by YangTe1** [django/channels_redis#143]
```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": ["redis://:xxx#xxxxx@ip:port/8"],
        },
    },
}
```
eg: my password has a “#” in it.
i tried replace it to "%23"
i tried urllib.parse.quote and quote_plus
all failed

**Comment by andrewgodwin** [comment]
You'll have to look at the documentation of the redis library we use - aioredis - to figure it out; we just pass the string through to that.

**Comment by YangTe1** [comment]
thx.  
aioredis's address can't support it, but it can set it separately.  
so finally, i tried: 
```
"hosts": [{"address": (host, port), "db": 8, "password": 'xxx'}]
```
and it was successful  

Maybe it's better to add it in document~ (#｀-_ゝ-)
