### ISSUE TITLE
Channels layer connect with AWS EC2

### ISSUE THREAD

**Issue by Suryanandsingh** [django/channels_redis#144]
How to connect **CHANNEL_LAYERS** config host on AWS ec2 ?

    CHANNEL_LAYERS = {
    'default': {
    'BACKEND': 'channels_redis.core.RedisChannelLayer',
    'CONFIG': {
             "hosts":[("<my_aws_host>", 6379)],
             },
         },
     }

I am trying like this.
please help me.
Thanks,

**Comment by andrewgodwin** [comment]
Sorry, but we can't help out with general support requests here - the issue tracker is for reproduceable bugs and
concrete feature requests only! Please see our support documentation (http://channels.readthedocs.io/en/latest/support.html)
for more information about where you can get general help.
