### ISSUE TITLE
Channel layers stop consuming messages from Redis

### ISSUE THREAD

**Issue by bashlakov** [django/channels_redis#145]
Hi!
I've experience a problem similar to #1191
To reproduce this problem I've build a sandbox project based on chat example from official tutorial, you can see it here: https://github.com/bashlakov/django-channels-bug-demo

Steps to reproduce the problem:

Open http://localhost:8000/chat and create a new chat.
Open this chat in another tab. You send message in one tab and see it in this and in second tab.
Create a new different chat in new tab and send message to it.
Come back to first chat tab and continue to send messages. After sending several messages the chat brakes down and you can't send any new massages.
At this point you can browse you Redis and see, that messages stored in specific.* channels queues but not consumed by channel layers.
There is a video with this steps: https://youtu.be/DTFE-Up1De0

I've tried this example on Mac and Linux, using latest version of packages and python 3.5.2.
I've also tried to start the project with ./manage.py runserver, daphne and even uvicorn with no luck.
I found in-memory channel layers backend in sources and check again using this implementation instead of channels_redis. I can't reproduce bug with in-memory backend, so I think the problem is related to channels_redis.
Can you please try to reproduce this problem in your environment and confirm issue?

**Comment by andrewgodwin** [comment]
I've just tried to reproduce this locally and it works perfectly, though I am also on Python 3.6. Could you try on 3.6? 3.5 has a few problems with async to the point where we may have to stop supporting it.

**Comment by bashlakov** [comment]
Confirm that upgrading python to 3.6 solve the problem. Not sure, is it correct to close this issue, because python 3.5 declared as supported version.

**Comment by andrewgodwin** [comment]
I think I might just say 3.6 is required then.

**Comment by d-s-e** [comment]
I just tried the test example with Python 3.5.4, and it seems to work.
So it would be great, if we could change the requirement from 3.6 to 3.5.4.
The reason is, I have my app running on a system with python 3.5, and it's not that easy to bring that to 3.6.

**Comment by carltongibson** [comment]
@d-s-e If you could pin this down to a specific change in 3.5.x that fixes the behaviour, and we can demonstrate that, then yeah, maybe we could lower the requirement. 

Having said that, it's swimming against the tide at this point, so it'd have to be convincing and I'm not sure how long we could maintain it going forward...

**Comment by d-s-e** [comment]
Hm, I didn't want to dig that deep ;-)
Fact is, it's working with 3.5.4 but not with 3.5.3.
So it has to be a fix introduced in 3.5.4.

**Comment by carltongibson** [comment]
Sure... but that's not quite enough to go on to say that we DO support the version, only to open up a whole raft of support requests and issues. It's just not worth it, we need to be sure.

**Comment by d-s-e** [comment]
Yes, you're right. But isn't just jumping direclty to 3.6 because "it works" just the same?
I don't have the time (and skills) to investigate this closer, so if this could cause trouble, just leave it as it is.
I have to pin to channels-redis 2.5.2 then.

**Comment by carltongibson** [comment]
Hi @d-s-e. It's more about capacity at this point. Unless someone can do the leg work we just can't revisit a previous decision here, especially given that Python 3.5 is now on the wane. (Django's just dropped it going forward, a [recent survey puts it at just 11% usage,](https://www.jetbrains.com/research/python-developers-survey-2018/#python-3-adoption) and so on.) Sorry.

**Comment by d-s-e** [comment]
I fully understand the capacity problem, I can see it with my own time. I just thought, this could help others, having the the same issue. But I'm fine with that, thanks.

**Comment by darkfishy** [comment]
I am facing exactly this issue, though on `Python 3.6.1`, with following installed packages (including their dependencies):
```
channels==2.1.7
channels-redis==2.3.3
django==2.1.7
mysqlclient==1.4.1
requests==2.21.0
```

Those who have somehow solved their issue, which minor version of `Python 3.6.y` did you use?

**Comment by nichoski** [comment]
It works well on Python 3.6.4. Just in case you have issues with 3.6.4 too,
of the other packages you listed, my versions are:
channels==2.1.6
channels-redis==2.3.2
Django==2.1.4
requests==2.21.0
I don't use mysql.

**Comment by darkfishy** [comment]
@nichoski That was pretty quick response :-) I'll test with 3.6.4 and report back as soon as I can. Thanks.

**Comment by darkfishy** [comment]
I tested with `Python 3.6.2`, `Python 3.6.3`, `Python 3.6.4` and `Python 3.6.8`.  It works from `3.6.4` onwards. However I haven't yet been able to find the underlying reason why it would stop on prior versions of Python.

**Comment by seocam** [comment]
Any suggestions to work that around with python 3.5.3 (current Python version in Debain 9)?

**Comment by m4rk3r** [comment]
I'm still experiencing this w/ both python `3.6.12` and python `3.8.2` has anyone else still running into this and have any possible workarounds?

**Comment by Kaju-Bubanja** [comment]
I'm also experiencing this with Python 3.6.6, so I'm not sure this issue is really related to the Python version, since different people report different versions to have it fixed for them. I think the problem lies somewhere else.
