### ISSUE TITLE
Update msgpack to 0.6.0

### ISSUE THREAD

**Issue by Marcelo-Theodoro** [django/channels_redis#146]
The msgpack release 0.6.0 fixed a security vulnerability related to DoS attack[1].

For now is not possible to update the msgpack when using channels_redis because it'll break compatibility.

What could be done to update the msgpack requirement?

[1] https://github.com/msgpack/msgpack-python/issues/295

msgpack changelog: https://github.com/msgpack/msgpack-python/blob/197e30723a242e3ba31f9634b3263ae4cb2937b1/ChangeLog.rst

**Comment by andrewgodwin** [comment]
Looks like it just needs a pull request to bump the requirement and check the tests pass.

**Comment by jroblak** [comment]
When can we expect a new release incorporating this change?

**Comment by andrewgodwin** [comment]
It's out in `2.3.3`.

**Comment by anx-ckreuzberger** [comment]
Sorry to re-open this, but 2.3.3 is only available for Python 3.6.

We are using Python 3.5 as it is the latest stable version available for Debian 9 (stretch, stable) - see https://packages.debian.org/search?keywords=python3 .

Would it be possible to provide a similar fix for Python 3.5?

**Comment by carltongibson** [comment]
Hi @anx-ckreuzberger. Not really... there are other reasons Python 3.5 was dropped. e.g. #145

**Comment by anx-ckreuzberger** [comment]
Ok, thanks for the info, I'll keep that in mind and I'll see if we can upgrade to Python 3.6 sonner than later.
