### ISSUE TITLE
No LICENSE file in PyPi package

### ISSUE THREAD

**Issue by d-s-e** [django/channels_redis#149]
I just noticed, that the LICENSE file is missing in the PyPi package. It should better be present there.

**Comment by carltongibson** [comment]
OK. Yes. Would (happily) take a PR on the MANIFEST.in ... 🙂

**Comment by carltongibson** [comment]
(I'll bet this is on Daphne too...)

**Comment by d-s-e** [comment]
See PR here #150

**Comment by carltongibson** [comment]
Closed by #150
