### ISSUE TITLE
asgiref dependency mismatch between channels and channels_redis

### ISSUE THREAD

**Issue by filipweidemann** [django/channels_redis#152]
Trying to update my dependencies and there seems to be a mismatch between channels and channels_redis.

Pipenv output:
`ERROR: Could not find a version that matches asgiref~=2.1,~=2.3,~=3.0`

Output of the responsible `pipenv graph` section:
```
channels-redis==2.3.2
  - aioredis [required: ~=1.0, installed: 1.2.0]
    - async-timeout [required: Any, installed: 3.0.1]
    - hiredis [required: Any, installed: 1.0.0]
  - asgiref [required: ~=2.1, installed: 2.3.2]
    - async-timeout [required: >=2.0,<4.0, installed: 3.0.1]
  - channels [required: ~=2.0, installed: 2.1.7]
    - asgiref [required: ~=2.3, installed: 2.3.2]
      - async-timeout [required: >=2.0,<4.0, installed: 3.0.1]
    - daphne [required: ~=2.2, installed: 2.2.5]
      - autobahn [required: >=0.18, installed: 19.3.3]
```

Is this already ongoing work or can something be done to help fixing this?

**Comment by LordGordonQ** [comment]
The latest updates to the Channels stack (`channels  2.1.7`) seems to have various conflicting requirements between asgiref, daphne, and channels-redis. See: https://github.com/django/channels/issues/1277


I'm able to satisfy all the dependencies with the following workaround:

```
asgiref<2.4
 #daphne<2.3
channels<2.2
```

**Comment by carltongibson** [comment]
New channels release is on the way. In the meantime you **can** update `asgiref` and ignore the error. 

```
pip install channels
pip install -U asgiref
```

The error message is misleading here. (It is compatible... daphne 2.3 does the work to wrap older apps...)

**Comment by carltongibson** [comment]
Going to close this here as it's better tracked on https://github.com/django/channels/issues/1277
