### ISSUE TITLE
`channels-redis 2.3.2 has requirement asgiref~=2.1, but you'll have asgiref 3.1.1 which is incompatible.` after updating almost everything

### ISSUE THREAD

**Issue by bastbnl** [django/channels_redis#156]
Hi,

I ran into an error after the daily update this morning and ran into this error:
```
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in /var/www/brownpapersession/dev/env/lib/python3.5/site-packages (from twisted>=18.7->daphne~=2.3->channels) (18.1.0)
Requirement already satisfied, skipping upgrade: txaio>=2.10.0 in /var/www/brownpapersession/dev/env/lib/python3.5/site-packages (from autobahn>=0.18->daphne~=2.3->channels) (2.10.0)
channels-redis 2.3.2 has requirement asgiref~=2.1, but you'll have asgiref 3.1.1 which is incompatible.
Installing collected packages: asgiref
  Found existing installation: asgiref 2.3.2
    Uninstalling asgiref-2.3.2:
      Successfully uninstalled asgiref-2.3.2
  Running setup.py install for asgiref ... done
Successfully installed asgiref-3.1.1

```

It seems that `pip` is unable to find the 2.4.0 release. I'm using python 3.5.3: 
```
(env) bastb@bastb-vps:/var/www/brownpapersession/dev/brownpapersession$ python --version
Python 3.5.3
```
The remaining stack:
```
aioredis==1.1.0
asgiref==3.1.1
...
channels==2.2.0
channels-redis==2.3.2
...
daphne==2.3.0
... 
Django==2.2
...
redis==3.2.1
...
```

I can tell the problem is caused by the python version I'm currently using, but there's a difference in the dependencies for daphne and channels itself. I can't and really don't want to move away from redis as I rely on `group_send` and I believe that's unavailable with the other backends. Wouldn't it be better to upgrade everything to python 3.6?

**Comment by carltongibson** [comment]
Yes, channels_redis hasn’t been compatible with Python 3.5 for a couple of releases now... 

You’re suggesting making 3.6 the minimum across the board? (To which, we, yes, maybe....)


At the least I suggest you update.

**Comment by carltongibson** [comment]
It seems here the setup.py install_requires are leading to more problems than they’re solving... 

ASGI v3 is fully backwards compatibilice. 

Daphne needed an update but channels and channels_redis were fine. Except pip complains. 

With hindsight we could have used different numbers but I can’t see how we can fix it going backwards. (Can’t change the packages.) 

I think dropping Python 3.5 was based on “it’ll look like it’ll work but it won’t.” — so can you force pip to install the new version, even though it doesn’t want to? (By specifying the exact version?)

**Comment by carltongibson** [comment]
I don’t think this is actionable. You need to update Python. 

But happy to hear suggestions.
