### ISSUE TITLE
The receive method is not scalable nor much more robust

### ISSUE THREAD

**Issue by joshuahaertel** [django/channels_redis#163]
The process local lock implemented at https://github.com/django/channels_redis/pull/117/commits/ce8450ae7d2d0f132486a1c319fb1325997999af means you can't safely scale up workers by starting new processes or servers.

The main consequence is that you will receive messages multiple times. For example, say one process moves the message that it's going to work on to the in flight list. Another process then might run the clean up script in `_brpop_with_clean` and move that message right back over to the pending list of messages to be processed. That message will then be processed twice.

The implementation also doesn't ensure that messages won't be dropped either, even in a single process. By calling the delete unconditionally after retrieving the message, as opposed to when the message is successfully processed, means that the message could be lost as it's processing. Perhaps the messages were too fast for @jberci to hit that race condition.

Personally, I think we should change the implementation to something like the adapters in the requests library. The default could be the original, push to a list, pull, don't worry about lost messages. If this solution works for @jberci, he can create his own custom adapter. I don't recommend something that won't scale and could both duplicate and drop jobs as something that should ship as the default. I personally would like to build an adapter that follows the reliability queue as explained in https://redis.io/commands/rpoplpush#pattern-reliable-queue and that uses a separate process to move jobs from processing back to pending if they haven't been deleted by a certain time included with each message.

I am willing to look into an implementation, if that's something you're interested.

**Comment by joshuahaertel** [comment]
I'm going to retract my offer to help out with this. I played around with `arq` and got what I needed.

I'm still not particularly fond of the current implementation though. If we were to use `LREM` to remove a job **after** it's completed, remove the process local lock and maybe a few other things to get it working more reliably, I would be happier. For now, it just feels like a complicated way to get similar/worse results.

I would suggest we go back to the simple implementation and if you need anything with better redundancy, use another library.

**Comment by carltongibson** [comment]
Hi @joshuahaertel. Thanks for your inputs here. Currently (unless you or someone wants to do the work) this isn't really in scope. (Just don't have the bandwidth for a rewrite here at this point.) 

It could be something we come back to...
