### ISSUE TITLE
ConnectionClosedError when layer is idle for longer than server timeout

### ISSUE THREAD

**Issue by flacerdk** [django/channels_redis#164]
The layer seems to fail when the Redis server is configured to have a timeout and the connection is kept idle for longer than that timeout. This is an issue when using `channels_redis` with a provider that uses a timeout in their instances (for example, Redis To Go sets a timeout of 150 seconds).

To reproduce, start a Redis server with a low timeout value set in `redis.conf`, say 20 seconds. Then run this code:

```python
import asyncio

from channels_redis.core import RedisChannelLayer


async def wait_and_send():
    layer = RedisChannelLayer(hosts=['redis://localhost:6379'])

    # should create new connection
    await layer.group_send('group', {'message': 'hi'})

    # wait for >timeout seconds
    await asyncio.sleep(25)

    # raises exception
    await layer.group_send('group', {'message': 'hi'})


loop = asyncio.get_event_loop()
loop.run_until_complete(wait_and_send())
``` 

When I run it I get:

```python
Traceback (most recent call last):
  File "break_channels_redis.py", line 14, in <module>
    loop.run_until_complete(wait_and_send())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "break_channels_redis.py", line 10, in wait_and_send
    await layer.group_send('group', {'message': 'hi'})  # raises exception
  File "/usr/local/lib/python3.7/site-packages/channels_redis/core.py", line 610, in group_send
    key, min=0, max=int(time.time()) - self.group_expiry
  File "/usr/local/lib/python3.7/site-packages/aioredis/commands/sorted_set.py", line 268, in zremrangebyscore
    return self.execute(b'ZREMRANGEBYSCORE', key, min, max)
  File "/usr/local/lib/python3.7/site-packages/aioredis/commands/__init__.py", line 51, in execute
    return self._pool_or_conn.execute(command, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aioredis/connection.py", line 322, in execute
    raise ConnectionClosedError(msg)
aioredis.errors.ConnectionClosedError: Reader at end of file
```

Following #26 I tried passing `socket_timeout` and `socket_keepalive` as query strings in the Redis URI but they don't seem to have any effect. #135 might also be related.

**Comment by oTree-org** [comment]
I am also observing the same issue with Heroku Redis, which has a 300 second timeout. So, in my settings.py, I specified a timeout of 280, to stay under Heroku's limit:

```
{
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [dict(address=REDIS_URL, timeout=280)]},
}
```
However, I continued to get the same error.

The result is that anytime a page is open for longer than 5 minutes, this error occurs. (When my pages load, they connect to a websocket consumer which adds them to a channel layer group, I think this is a very ordinary setup.)

**Comment by LincolnPuzey** [comment]
I had a similar Issue, except when using `self.channel_layer.send()` from a AsyncConsumer.

This was using redis hosted locally with timeout set to 30.

The following traceback occured when I create an instance of a AsyncConsumer (eg connect a websocket), then wait 30+ seconds, then do something causing `self.channel_layer.send()` to be called.

```
Traceback (most recent call last):
...
  File "/home/.../lib/python3.7/site-packages/channels_redis/core.py", line 296, in send
    if await connection.llen(channel_key) >= self.get_capacity(channel):
  File "/home/.../lib/python3.7/site-packages/aioredis/commands/list.py", line 70, in llen
    return self.execute(b'LLEN', key)
  File "/home/.../lib/python3.7/site-packages/aioredis/commands/__init__.py", line 51, in execute
    return self._pool_or_conn.execute(command, *args, **kwargs)
  File "/home/.../lib/python3.7/site-packages/aioredis/connection.py", line 319, in execute
    raise ConnectionClosedError(msg)
aioredis.errors.ConnectionClosedError: Reader at end of file
```

**Comment by LincolnPuzey** [comment]
Seems to be an issue where the connection returned by `RedisChannelLayer.connection()` is closed, but is then used anyway.

![Screenshot from 2019-11-14 16-59-28](https://user-images.githubusercontent.com/18750802/68842063-b2d63a80-0700-11ea-8d96-c4fad4c80b66.png)

My current workaround is to catch the `ConnectionClosedError` and retry the `self.channel_layer.send()` which seems to work because in the retry call of `send`, `conns` is an empty list, and `conns.append(await aioredis.create_redis(**self.host, loop=loop))` is run again.

However this seems like something that should be handled in channels_redis

**Comment by LincolnPuzey** [comment]
My better workaround: subclass `RedisChannelLayer` and have my own `ConnectionContextManager` that doesn't return a closed connection

```python
class MyRedisChannelLayer(RedisChannelLayer):
    class ConnectionContextManager:
        def __init__(self, pool):
            self.pool = pool

        async def __aenter__(self):
            conn = await self.pool.pop()

            # check if the connection is closed
            if conn.closed:
                # if so, discard it and get a new one.
                self.pool.conn_error(conn)
                conn = await self.pool.pop()

            self.conn = conn
            return self.conn

        async def __aexit__(self, exc_type, exc, tb):
            if exc:
                self.pool.conn_error(self.conn)
            else:
                self.pool.push(self.conn)
            self.conn = None
```

Are there potential issues with this approach?

**Comment by WilliamWCYoung** [comment]
@LincolnPuzey - you might want to recurrsively attempt to get a connection as your implementation would fail if the second connection you 'pop' from the pool is dead as well:
```python
class MyRedisChannelLayer(RedisChannelLayer):
    class ConnectionContextManager:
        def __init__(self, pool):
            self.pool = pool

        async def __aenter__(self):
            conn = await self.pool.pop()

            # check if the connection is closed
            if conn.closed:
                # if so, discard it and get a new one.
                self.pool.conn_error(conn)
                return await self.__aenter__()

            self.conn = conn
            return self.conn

        async def __aexit__(self, exc_type, exc, tb):
            if exc:
                self.pool.conn_error(self.conn)
            else:
                self.pool.push(self.conn)
            self.conn = None
```

**Comment by LincolnPuzey** [comment]
@WilliamWCYoung , good point, though to me recursively calling `__aenter__()` seems unpythonic and unintuitive.

Perhaps a while loop calling `self.pool.pop()` until an open connection is retrieved would be better. 

Though then if something has gone wrong with redis and we get closed connections forever - we'll end up with an infinite loop or infinite recursive calls.

**Comment by WisdomPill** [comment]
@LincolnPuzey I agree, there souls be an upper limit on retries. 

Can you make a PR for this issue? Is it testable?

**Comment by Rusox89** [comment]
The underlying implementation of `ConnectionPool` will avoid infinite recursion as if there are no more connections on the pool it will await and try to open one, if Redis is not responding I expect to see some socket timeout exceptions coming from `aioredis.create_connection` hence avoiding infinite recursion

**Comment by LincolnPuzey** [comment]
If I was to make a PR I would probably make changes to `ConnectionPool` to ensure `.pop()` doesn't return a closed connection. For the workaround above, I did it that way because it was possible to subclass `RedisChannelLayer` and use that subclass as the backend in the `CHANNEL_LAYERS` setting.

**Comment by Rusox89** [comment]
@LincolnPuzey this might work
`class ConnectionPool

    ...

    async def pop(self, loop=None):
        """
        Get a connection for the given identifier and loop.
        """
        conns, loop = self._ensure_loop(loop)

        if not conns:
            conns.append(await aioredis.create_redis(**self.host, loop=loop))
        
        conn = conns.pop()

        if conn.closed:
            conn = await self.pop(loop=loop)
            return conn

        self.in_use[conn] = loop
        return conn

    ...
```

**Comment by Rusox89** [comment]
#178

**Comment by LincolnPuzey** [comment]
Thanks @Rusox89  for the PR.

After coming back to this I think that in an async environment the [LBYL](https://docs.python.org/3/glossary.html#term-lbyl) approach is not the best fit. We check if the connection is open in one task, and then `n` tasks later, attempt to use it.

There is always the possibility the connection could be closed from server side in that time. This would lead to very rare, hard to reproduce errors.

This PR certainly makes the chance of an error much less, but there is still the possibility.
