### ISSUE TITLE
SSL error for self signed cert

### ISSUE THREAD

**Issue by hibare** [django/channels_redis#168]
Hi,

channels do not support redis having mutual authentication using custom CA signed certs. 

Despite setting SSL_CERT_DIR and SSL_CERT_FILE to correct CAs, channels fails to validate the certificate.

This happens only for async_to_sync(channel_layer.send)(channelName,  function. self.send works fine as expected.

**Comment by carltongibson** [comment]
Hi. 

Can you provide a project with exact steps to reproduce the issue here? (With the info given it's not clear where even to begin...) 

Happy to reopen if you can provide the extra detail.
