### ISSUE TITLE
Document unix:///path format for redis config

### ISSUE THREAD

**Issue by cwassert** [django/channels_redis#18]
Redis supports unix domain sockets, which are [slightly faster](http://redis.io/topics/benchmarks) than a loopback tcp connection. The [redis python bindings](https://pypi.python.org/pypi/redis) have direct support for this. So it should be very easy to add.

I propose the following syntax in order to keep the current syntax untouched.
```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgi_redis.RedisChannelLayer",
        "CONFIG": {
            "unix": ["/path/to/redis.sock"],
        },
        "ROUTING": "my_project.routing.channel_routing",
    },
}
```

**Comment by andrewgodwin** [comment]
Have you tried using the URI form and passing a single host of `"unix:///path/to/socket"`? Connection strings like that get passed down to the python binding directly so if it has a URI form that can be used with no changes.

**Comment by cwassert** [comment]
Using `"hosts": ['unix:///tmp/redis.sock']` does work!

I did not try that because there is an extra keyword argument for it, i.e. `redis.Redis(unix_socket_path='/tmp/redis.sock')`.

Thank you. Maybe you should add this example to the documentation.

**Comment by andrewgodwin** [comment]
Agreed, I'll change the ticket to reflect that.
