### ISSUE TITLE
aioredis seems dead

### ISSUE THREAD

**Issue by si14** [django/channels_redis#194]
It looks like `aioredis` fails tests on 3.8 for quite some time and its maintainers aren't keen to fix it https://github.com/aio-libs/aioredis/issues/721

Last non-trivial merged PR is at least half a year old https://github.com/aio-libs/aioredis/pulls?page=2&q=is%3Apr+is%3Aclosed

Seems that `aioredis` is flatlining. Do you folks have a plan (b)? Channels is the future of Django, so it is a bit worrying to have a problematic dependency in its core.

Sorry if this issue is not concrete enough, please feel free to remove it if it's unacceptable.

**Comment by carltongibson** [comment]
Hi @si14. 

No, good issue. Thanks for the report. 

Channels is an add on to Django, rather than the future per se. But still...

Short answer is No. we need to look into it. What is the go to option for async Python Redis if aioredis is no longer it? 

Looking into that is step one. Then a small abstraction above the underlying library if needed as step two.

**Comment by qeternity** [comment]
> What is the go to option for async Python Redis if aioredis is no longer it?

I would say aredis, which has cluster/sentinel support which would be a big win for channels.

https://github.com/NoneGG/aredis

**Comment by Andrew-Chen-Wang** [comment]
Aioredis is currently being revived with several PRs being merged, including support for Python 3.8 and 3.9 (CI passing). Hopefully that helps in this process :)

**Comment by qeternity** [comment]
aioredis still leaves much to be desired (3.9 support is bare minimum). I've done an aredis migration here: https://github.com/django/channels_redis/pull/195

@carltongibson I've been slammed recently, I'm sure like everyone else, but will have some downtime over holidays to lend a hand.

**Comment by carltongibson** [comment]
Hey @qeternity — no stress! It's meant to be fun. 

This year of all years (but all years!) we get there when we get there. 

It we were ready with a new version by the (picking a date from the air) the Spring, that would be absolutely super, and would hopefully allow space to take time off over the holiday!

Self-care is strictly greater than replacing the redis backend. 😃 

But as you have bandwidth, yes, super. 🏅

**Comment by qeternity** [comment]
@carltongibson wicked, see you on the other side.

**Comment by carltongibson** [comment]
I think it's alive again. 

v2.0.0a1 was tagged recently and there's a pinned issue on the migration. https://github.com/aio-libs/aioredis-py/issues/930

I'm going to close this for now. Happy to look at PRs allowing multiple backends if anyone wants to put that effort in.
