### ISSUE TITLE
New version. Use CalVer?

### ISSUE THREAD

**Issue by carltongibson** [django/channels_redis#200]
Hey @andrewgodwin. 

I want to release a new version before the end of the week.

Wondering about the version number...

See the Change log. 

It’s all backwards compatible, except bumping the msg pack dependency, so I’d just call it 2.5 and be done. 

But then there’s that dependency, so maybe 3. 

But the hopefully we perhaps merge #195 before the autumn, and then do we have to jump to 4 (so soon) 

Numbers are cheap of course. 

But I’m kind of a bit Meh with SemVer. 

I’ve been taken by the arguments for CalVer recently, and wonder if it isn’t better just to use that, and be clear in the release notes, maintaining BC wherever feasible. 

So version would be 2020.7.0 on that basis. 

Can I ask for your guidance? Thanks. C.

**Comment by andrewgodwin** [comment]
I don't mind at all - the only thing with SemVer is that there's some built-in support for it with Python package tooling (e.g. `~=4.3`).

I personally just happily increase the major number whenever and don't feel bad about it, but if you think CalVer is more appropriate, I could get behind that.

**Comment by carltongibson** [comment]
OK, thanks Andrew. 

Let’s go for v3 now then. It’ll be good to stretch my comfort zones. (“They are only numbers” can be my mantra of the week. 💆‍♂️)

**Comment by carltongibson** [comment]
Closed in 08989d1cc5c4a1b2af15e0c380bab6e29bdece23
