### ISSUE TITLE
Upgrade from channels-redis==2.4.2 to channels-redis==3.0.0

### ISSUE THREAD

**Issue by jlariza** [django/channels_redis#206]
Good day,

We are using two apps using django channels. The server uses Nginx and daphne; and starts daphne using supervisor with this configuration

```
[program:daphne_app]
directory=path/to/app
command=/home/ubuntu/.envs/app/bin/daphne config.asgi:application --http-timeout 600 --unix-socket /tmp/daphne-app.sock
autorestart=true
```

It was working as expected, but when we upgraded the version package the websocket stopped working. It does not raise errors or logs, it simply died.

Is there an upgrading guide to check what we would need to update in our configuration to install latest version?

Thank you

**Comment by carltongibson** [comment]
Check you Redis version. Lots of people are using old versions and hitting problems. You’ll need version 5 or 6, which are the supported versions according to Redis’ policy.

**Comment by jlariza** [comment]
@carltongibson I tried using it with redis 6 but it still not worked. I started checking what is happening and it seems to be an issue with `async_to_sync` from `asgiref.sync`. For some reason, using channels-redis v3 `async_to_sync` returns None so the connection with the websocket is killed just after it has been stablished.

I tried using latest `redis-server` , latest `channels-redis` and latest `asgiref` versions. Any idea what may be happening?

**Comment by carltongibson** [comment]
Hi @jlariza — Thanks for the follow up. 

No idea as yet. Can you reproduce the issue in a sample project? 

Failing that, **some** more detail is going to be needed...

> I started checking what is happening and it seems to be an issue with async_to_sync from asgiref.sync. For some reason, using channels-redis v3 async_to_sync returns None so the connection with the websocket is killed just after it has been stablished.

Exactly were do you mean, and what are you seeing? Impossible to say anything without more details. (We quickly end up back at the need for a reproduce, but let's see how close we can get. 🙂)

**Comment by rarenatoe** [comment]
@jlariza Did you ever fix this? How did you manage to install version 5 or 6?
@carltongibson  I only found [this](https://pypi.org/project/redis/) and [this](https://pypi.org/project/redis3).
Both of them don't go past 3.5

I changed to `redis3` but still no luck.
