### ISSUE TITLE
ReplyError generic ASGI request: ERR Error running script @user_script:4: @user_script: 4: Wrong number of args calling Redis command From Lua script

### ISSUE THREAD

**Issue by babu-upcomer** [django/channels_redis#208]
The following errors getting reported after updating to 3.0.0,

```
ReplyError
ERR Error running script (call to f_3795502f95ab9f727df969c36bb2acc43ea2dc87): @user_script:4: @user_script: 4: Wrong number of args calling Redis command From Lua script

ReplyError: ERR Error running script (call to f_3795502f95ab9f727df969c36bb2acc43ea2dc87): @user_script:4: @user_script: 4: Wrong number of args calling Redis command From Lua script 
  File "channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "channels/utils.py", line 58, in await_many_dispatch
    await task
  File "channels/utils.py", line 50, in await_many_dispatch
    result = task.result()
  File "channels_redis/core.py", line 453, in receive
    real_channel
  File "channels_redis/core.py", line 508, in receive_single
    index, channel_key, timeout=self.brpop_timeout
  File "channels_redis/core.py", line 343, in _brpop_with_clean
    await connection.eval(cleanup_script, keys=[], args=[channel, backup_queue])
```
![Annotation 2020-07-11 152006](https://user-images.githubusercontent.com/19949828/87221493-0a10d580-c38a-11ea-85ad-81af670817c3.png)

- Python 3.7 with Redis 5
- Channel 2.4.0 with Django 3.0.8
- Uvicorn with uvloop
- Attaching the screenshot from sentry

**Comment by carltongibson** [comment]
Any chance you could narrow this down to a reproduce?

Does it continue, or is it one time only? 
Did you try to run `SCRIPT FLUSH`? Any change?

**Comment by babu-upcomer** [comment]
Thanks for responding! It happened a couple of times against AWS Elasticache Redis 5.0.6. Not a continuous one though. I ignored the first one considering that it could one time. Not sure how could I run `SCRIPT FLUSH` as we cannot CLI into elasticache outside AWS network. If you mean to just flush all db I can try that but that's not gonna be an ideal solution anyway.

**Comment by carltongibson** [comment]
Hmm. I don't know about Elasticache... 🧐 

We adjusted the lua scripts to improve those for 3.0, so flushing them might be needed. 

(Would imagine the cache would clear on an error, maybe Elasticache gives you a couple of instances?)

**Comment by carltongibson** [comment]
SCRIPT FLUSH is just the single command, not clearing the whole DB. That seems a bit drastic, but would like do that job.  😬

**Comment by babu-upcomer** [comment]
Sorry for being less in context. Yeah elasticache can be only connected via CLI through a jumpbox AWS EC2 instance. And regarding flushing I think the error getting reported is on the 3.0.0 version of core.py. That is, at ` File "channels_redis/core.py", line 343, in _brpop_with_clean` which matches the master. The screenshot shows the latest script string too. I do not know much about Redis advanced commands and Lua scripts else would have come up with more helpful info. Thanks again for the quickly responses.

**Comment by carltongibson** [comment]
Hi @babu-upcomer. No problem. If there's an issue we'd like to track it down. 

Can I double check, I'm not sure what the status is: are you still seeing the issue, or did it disappear after a number of times? 

Thanks.

**Comment by babu-upcomer** [comment]
@carltongibson It disappears after some time. To me it looks like it happens when there is a cold start. For example, we have live sessions each day in our app, but there were no sessions for the last couple of days before this happened. It happened at our staging first and the at prod(both have different Redis instances configured). I'm yet to confirm if this happens next time in the same environment but unfortunately we do not have any for the next few days.

**Comment by carltongibson** [comment]
OK... — Let's leave this open for now. If it comes back, if we can try to pin down an exact reproduce we'll can work out what's happening. Thanks.

**Comment by stefanw** [comment]
I'm seeing the same error. This line is calling the Redis command [`ZADD`](https://redis.io/commands/zadd) but it seems to be missing an argument:

https://github.com/django/channels_redis/blob/8e1476eb335b9e60028bce24851e79babee9dbab/channels_redis/core.py#L335

The Redis docs state that the syntax is:
```
ZADD key [NX|XX] [CH] [INCR] score member [score member ...]
```

It seems like you need to call `ZRANGE` with the additional `WITHSCORES` parameter to get scores to add in the `ZADD` call.

**Comment by stefanw** [comment]
I reduced the delay in `test_receive_cancel` and can now reproduce the error in tests:

https://travis-ci.org/github/stefanw/channels_redis/jobs/707792088

**Comment by stefanw** [comment]
[Pull Request for your consideration.](https://github.com/django/channels_redis/pull/209).

**Comment by wmorrell** [comment]
I started seeing this in CI after upgrading to 3.0.0. I wasn't always seeing it in local environment, which has a Redis instance that sticks around, vs the CI that launches a new empty server each run. So it does seem to be something around cold start and timing.

**Comment by carltongibson** [comment]
3.0.1 should address this and is now available on PyPI https://pypi.org/project/channels-redis/3.0.1/. 

Thanks all for the input. 🏅
