### ISSUE TITLE
aioredis.errors.ReplyError: ERR unknown command 'BZPOPMIN'

### ISSUE THREAD

**Issue by sharon-samson** [django/channels_redis#211]
Iam working in a django project with channels,where I need to use redis channel layers.Whenever I try to connect using websocket client it is showing below error.

**Error**
 Exception inside application: ERR unknown command 'BZPOPMIN'
Traceback (most recent call last):
  File "/home/dev/integrated_module/myvenv/lib/python3.8/site-packages/channels/sessions.py", line 183, in __call__
    return await self.inner(receive, self.send)
  File "/home/dev/integrated_module/myvenv/lib/python3.8/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/home/dev/integrated_module/myvenv/lib/python3.8/site-packages/channels/utils.py", line 58, in await_many_dispatch
    await task
  File "/home/dev/integrated_module/myvenv/lib/python3.8/site-packages/channels/utils.py", line 50, in await_many_dispatch
    result = task.result()
  File "/home/dev/integrated_module/myvenv/lib/python3.8/site-packages/channels_redis/core.py", line 452, in receive
    message_channel, message = await self.receive_single(
  File "/home/dev/integrated_module/myvenv/lib/python3.8/site-packages/channels_redis/core.py", line 507, in receive_single
    content = await self._brpop_with_clean(
  File "/home/dev/integrated_module/myvenv/lib/python3.8/site-packages/channels_redis/core.py", line 345, in _brpop_with_clean
    result = await connection.bzpopmin(channel, timeout=timeout)
aioredis.errors.ReplyError: ERR unknown command 'BZPOPMIN'

**In setting.py,**

```CHANNEL_LAYERS = {
   "default": {
     "BACKEND": "channels_redis.core.RedisChannelLayer",
       "CONFIG": {
          "hosts": [("localhost", 6379)],
       },
   },
}

**pip freeze**

absl-py==0.9.0
aioamqp==0.14.0
aioredis==1.3.1
amqp==2.6.0
asgi-redis==1.4.3
asgiref==3.2.3
astunparse==1.6.3
async-timeout==3.0.1
attrs==19.3.0
autobahn==20.7.1
Automat==20.2.0
billiard==3.6.3.0
cachetools==4.1.1
celery==4.4.6
certifi==2020.4.5.1
cffi==1.14.0
channels==2.4.0
channels-rabbitmq==1.2.1
channels-redis==3.0.1
chardet==3.0.4
constantly==15.1.0
cryptography==2.9.2
daphne==2.5.0
decorator==4.4.2
Django==3.0.7
django-celery-results==1.2.1
django-channels==0.7.0
django-redis==4.12.1
django-social-share==1.4.0
djangorestframework==3.11.0
future==0.18.2
gast==0.3.3
google-auth==1.19.2
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.30.0
h5py==2.10.0
hiredis==1.1.0
hyperlink==19.0.0
idna==2.9
imageio==2.8.0
imageio-ffmpeg==0.4.2
importlib-metadata==1.7.0
incremental==17.5.0
Keras==2.4.3
Keras-Preprocessing==1.1.2
kombu==4.6.11
Markdown==3.2.2
migrate==0.3.8
moviepy==1.0.3
msgpack==1.0.0
msgpack-python==0.5.6
mtcnn==0.1.0
numpy==1.18.5
oauthlib==3.1.0
opencv-python==4.2.0.34
opt-einsum==3.3.0
pamqp==2.3.0
Pillow==7.1.2
pkg-resources==0.0.0
proglog==0.1.9
protobuf==3.12.2
psycopg2-binary==2.8.5
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
PyHamcrest==2.0.2
pyOpenSSL==19.1.0
pytz==2020.1
PyYAML==5.3.1
redis==2.10.6
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.6
scipy==1.4.1
service-identity==18.1.0
six==1.15.0
sqlparse==0.3.1
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorflow==2.2.0
tensorflow-cpu==2.2.0
tensorflow-estimator==2.2.0
termcolor==1.1.0
tqdm==4.46.1
Twisted==20.3.0
txaio==20.4.1
urllib3==1.25.9
vine==1.3.0
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.1.0
zope.interface==5.1.0


**Ubuntu OS**
18.0

**Currently working** in local environment ,
**runcommand is** python manage.py runserver

**Comment by carltongibson** [comment]
Check your Redis version. You may need to update.

**Comment by sharon-samson** [comment]
I gave this method to update redis version
wget http://download.redis.io/releases/redis-5.0.5.tar.gz
tar xzf redis-5.0.5.tar.gz
cd redis-5.0.5
make
src/redis-server

Output:
362:C 23 Jul 2020 05:59:06.522 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
362:C 23 Jul 2020 05:59:06.522 # Redis version=5.0.5, bits=64, commit=d2082430, modified=1, pid=362, just started
362:C 23 Jul 2020 05:59:06.522 # Warning: no config file specified, using the default config. In order to specify a config file use src/redis-server /path/to/redis.conf
362:M 23 Jul 2020 05:59:06.524 * Increased maximum number of open files to 10032 (it was originally set to 1024).
362:M 23 Jul 2020 05:59:06.524 # Could not create server TCP listening socket *:6379: bind: Address already in use


If i gave redis-server after the above process it shows
1746:C 23 Jul 05:59:22.289 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1746:C 23 Jul 05:59:22.289 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=1746, just started
1746:C 23 Jul 05:59:22.289 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1746:M 23 Jul 05:59:22.290 * Increased maximum number of open files to 10032 (it was originally set to 1024).
1746:M 23 Jul 05:59:22.290 # Creating Server TCP listening socket *:6379: bind: Address already in use

So now the default which will use in my project by django will be 4.0.9 version right?

**Comment by carltongibson** [comment]
> # Creating Server TCP listening socket *:6379: bind: Address already in use

Looks like you didn't shut down the old instance.

**Comment by sharon-samson** [comment]
Yeah thanks for the suggestion...I done as you said..now when i give redis-server,it is giving version 5
but iam getting this error
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 6379, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 6379)



I checked for error the solution was to restart server. I restarted but version 4 is getting restarted again..
Can you suggest any solution?

**Comment by carltongibson** [comment]
Check your paths. Make sure you're staring the right binary. 

This isn't really an issue we can help you with here. You just need to go slowly and double check your steps at each point.

**Comment by sharon-samson** [comment]
Yes it was my path issue...I changed it and working now!!!
I removed my old version as well
Now if I give redis-server(it shows version 5)
and when I listen to the port it shows
redis-ser 24955             dev    6u  IPv6 15204718      0t0  TCP *:6379 (LISTEN)
redis-ser 24955             dev    7u  IPv4 15204719      0t0  TCP *:6379 (LISTEN)


But it will show whenever I run the command redis-server

If I stop the server using CTRL+C and do listening to the port there is no port which listen to redis-server

It should listen by default even Iam not run the redis-server command right?
Where am I missing?

**Comment by sharon-samson** [comment]
I followed https://redis.io/topics/quickstart
for my current issue...
It is working fine now
Thankyou for your suggestion ...@carltongibson
