### ISSUE TITLE
Issue with group_send when user sending the message

### ISSUE THREAD

**Issue by umang1995** [django/channels_redis#225]
**OS** - Ubuntu 18.04.4 LTS
**Browser** - Google chrome
**A `pip freeze` output showing your package versions -(Attached) 
[freezeoutput.txt](https://github.com/django/channels_redis/files/5212168/freezeoutput.txt)
** 

**How you're running Channels (runserver? daphne/runworker? Nginx/Apache in front?)** - 
Nginx -> daphne(systemd process) used for both HTTP and socket connections

- What you expected to happen vs. what actually happened - 
Scenario -> 
I am trying to build a multiplayer game (like bingo) 
a user comes and creates a room for the game. (he is added to a group)
other users use the room id created to join in the room (they are also added to the group).
When the user enters the room ( server sends a group message to everyone which updates the joined players in the room)

Once Everyone Joins the game and the creator sends a ping to the server to distribute the bingo ticket. (This step also works as expected)

Once everyone gets the tickets then the creator sends another ping to the server and the server then has to send a number at an interval of 7 seconds.

**This is the step which is deviating from my expectation**
Expected Result - Everyone should get the numbers.
Actual Result - Everyone except the creator gets the numbers. (I have written a console.log to check if the WebSocket connection is closed) but that is not happening. Checking server logs also not getting any pings. ( I am not able to understand the reason for this odd behavior) 

- Console logs and full tracebacks of any errors

No Errors are being reported in the log files

**Comment by sevdog** [comment]
From your requirements file it seems you have installed two different versions of channels:

```
channels==2.4.0
django-channels==0.7.0
```

Have you tried removing the old one (`0.7.0`)?
