### ISSUE TITLE
aioredis.errors.ReplyError: ERR unknown command 'BZPOPMIN'

### ISSUE THREAD

**Issue by iamnotagentleman** [django/channels_redis#234]
Runtime: Python 3.8

OS: Windows 10(Client-Side) & Docker WSL (Server-Side)

Redis: Redis server v=5.0.10 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=bbb052a4486dea7a

Installed Packages (PIP freeze output);
```
Automat==20.2.0
cffi==1.14.4
channels==3.0.2
channels-redis==3.2.0
constantly==15.1.0

daphne==3.0.1
Django==3.1.4
hiredis==1.1.0
hyperlink==20.0.1
idna==2.10
incremental==17.5.0
msgpack==1.0.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
PyHamcrest==2.0.2
pyOpenSSL==20.0.1
pytz==2020.4
service-identity==18.1.0
six==1.15.0
sqlparse==0.4.1
Twisted==20.3.0
txaio==20.12.1
zope.interface==5.2.0
```

How you're running Channels: with runserver, also tried with python interpreter

What you expected to happen vs. what actually happened?:

I follow the channels tutorial, in section 2 [Channels-layer-section](https://channels.readthedocs.io/en/stable/tutorial/part_2.html) but when I try these snippet
```
import channels.layers
channel_layer = channels.layers.get_channel_layer()
from asgiref.sync import async_to_sync
async_to_sync(channel_layer.send)('test_channel', {'type': 'hello'})
async_to_sync(channel_layer.receive)('test_channel')

```
Encounter the aioredis.errors.ReplyError: ERR unknown command 'BZPOPMIN'

I check the BZPOPMIN from the redis docs, docs says Available since 5.0.0.  I meet thıs prerequisites, 

I reckon this problem is caused by the WSL infrastructure.

re-check BZPOPMIN Availablity with redis-cli
output:
```
# redis-cli
127.0.0.1:6379> ZADD zset1 0 a 1 b 2 c
(integer) 3
127.0.0.1:6379> BZPOPMIN zset1 zset2 0
1) "zset1"
2) "a"
3) "0"
```

**Comment by iamnotagentleman** [comment]
Problem Solved. There was a conflict because of rabbitmq.

**Comment by Aleksi44** [comment]
@iamnotagentleman 

Can you tell me what you did to fix the problem? 
I also have a rabbitmq service running but I want to keep it.
