### ISSUE TITLE
RuntimeError: dictionary keys changed during iteration

### ISSUE THREAD

**Issue by encetamasb** [django/channels_redis#243]
Sometimes I can see the following error in the logs:

      ...
      File "/usr/local/lib/python3.8/site-packages/channels_redis/core.py", line 122, in close_loop
        for k, v in self.in_use.items():
    RuntimeError: dictionary keys changed during iteration

I don't use the latest redis_channel package, but I can see the same loop construct in current master as well:
 
https://github.com/django/channels_redis/blob/38ffdeb610ce175a01698ca267a6cccc171043c9/channels_redis/core.py#L125

        for k, v in self.in_use.items():
            if v is loop:
                self.in_use[k] = None

According to the python3 docs:

       Iterating views while adding or deleting entries in the dictionary 
       may raise a RuntimeError or fail to iterate over all entries. 

I'm happy to send a patch to set key as `None` out of for loop, although I'm a bit confused by the construct itself.

**Comment by carltongibson** [comment]
Hi @encetamasb — yes, this seems valid, thanks. 

At a quick glance, making a copy to iterate may be sufficient… 🤔 
(I need to review why we don't `del self.in_use[k]` here also.)

**Comment by carltongibson** [comment]
Fixed by https://github.com/django/channels_redis/pull/316
