### ISSUE TITLE
Send message to all groups match a pattern

### ISSUE THREAD

**Issue by shahriarshm** [django/channels_redis#249]
I wonder if there is a way to send a message to all groups match a specific pattern. The method may be like this:
``` python
# Say 'hello' to all users that their names start with 'a'
channel_layer.group_match_send('user_a*', {'type': 'user.notify', 'notification': 'hello!'})
```
I did the patch using [scan](https://redis.io/commands/scan) method on redis. I can make PR if maintainers are interested.

**Comment by carltongibson** [comment]
Hi @shahriarshm — thanks for the suggestion. 

I don't think expanding the channel layer API is a good thing here. (Rather subscribe users to multiple groups…) However, there's nothing stopping you doing this in your own project.
