### ISSUE TITLE
Support out-of-process "group_add" and "group_discard" for PubSub channel layer

### ISSUE THREAD

**Issue by jalaziz** [django/channels_redis#264]
In #247, [this comment](https://github.com/django/channels_redis/pull/247#issuecomment-828754146) explain why the initial implementation of the PubSub channel layer does not support out-of-process `group_add` (and by extension, `group_discard`).

However, I believe this is a bigger limitation than it might seem at first. In our case, the issue is not so much a consumer subscribing a `different` consumer, but rather being able to dynamically subscribe and unsubscribe a consumer from normal HTTP activity.

In our case, this comes into play in a couple different scenarios:

- When an admin disables a user, we clean up the existing group subscriptions. This is done from whatever HTTP server receives the request.
- When a user's permission change, we subscribe or unsubscribe them from certain groups. This allows for a very dynamic, near real-time experience, without the need for the client refreshing or reconnecting.

I do realize that both these scenarios are possible by sending the Consumers a custom "command" message to have them call `group_add` and `group_discard` in-process, but it would be nice to not have to add the extra logic in our app layer for something this foundational.

**Comment by qeternity** [comment]
I think this is going to be a fundamental limitation of pubsub as opposed to anything specific to the implementation.

**Comment by jalaziz** [comment]
Yeah, to be fair, I haven't given much thought to how it could work with pubsub. I also haven't yet tried the workaround I outlined above.

Hope to get to it this weekend to get a better idea of how big of a limitation this is.

**Comment by qeternity** [comment]
The workaround you mention _should_ be the proper way to handle it. It cleaner.

The method you're current using is possible through sheer accident of redis architecture at the time.

**Comment by acu192** [comment]
> I do realize that both these scenarios are possible by sending the Consumers a custom "command" message to have them call group_add and group_discard in-process, but it would be nice to not have to add the extra logic in our app layer for something this foundational.

Yes, IMO this is how it should be done. If you know the channel name of a consumer (seems that you do), it is safe to call `this.channel_layer.send(...)` using the pubsub impl to send a message directly to that consumer. That will work fine. In turn, that consumer can do its own `group_add` and `group_discard`. (I know you have this in mind already, I'm just reiterating the idea for posterity.)

Definitely less convenient, but IMO it's the most robust way to solve it.

**Comment by jalaziz** [comment]
Closing this as the workaround of sending messages back to the original consumer to manage groups seems to work fine.
