### ISSUE TITLE
Channels' worker fails to start with PubSub layer 

### ISSUE THREAD

**Issue by jbprld** [django/channels_redis#270]
Hello,

With the new pubsub layer, Channels worker fails to start due to the following error:

`RuntimeError: You should only call receive() on channels that you "own" and that were created with new_channel()`
from [here](https://github.com/django/channels/blob/main/channels/worker.py#L37)

I can patch the Worker's [handle function](https://github.com/django/channels/blob/main/channels/worker.py#L26) by replicating the logic of [.new_channel()](https://github.com/django/channels_redis/blob/main/channels_redis/pubsub.py#L146) for each channel but it seems like a hack.

Is it an expected behavior with the new pubsub logic? If not should it be fixed in channels or channels_redis ?

Thank you.

**Comment by jbprld** [comment]
Any news regarding this issue ?

**Comment by jbprld** [comment]
I'm talking about https://channels.readthedocs.io/en/stable/topics/worker.html
When launching the worker with `python manage.py runworker my_channel`, the command just fails because it's calling `receive()` without creating the channel in the first place with `new_channel()`

**Comment by acu192** [comment]
Okay I see now what you mean.

I've studied it a bit this morning. I _think_ [this raised exception](https://github.com/django/channels_redis/blob/1132fccbaf924f705321dae69bb53ff0d13ac81d/channels_redis/pubsub.py#L179-L181) can be replaced by something like the following:

```python
        self.channels[channel] = asyncio.Queue()
        shard = self._get_shard(channel)
        await shard.subscribe(channel)
```

That is, if `receive()` is called with a channel name it doesn't expect, it can subscribe to that channel on-demand and continue on its way. That _should_ work fine.

I don't have any spare cycles right now. Can you experiment with this idea and post back here if it solves your problem? If so, we can look at doing a PR to fix this.

**Comment by jalaziz** [comment]
> Okay I see now what you mean.
> 
> I've studied it a bit this morning. I _think_ [this raised exception](https://github.com/django/channels_redis/blob/1132fccbaf924f705321dae69bb53ff0d13ac81d/channels_redis/pubsub.py#L179-L181) can be replaced by something like the following:
> 
> ```python
>         self.channels[channel] = asyncio.Queue()
>         shard = self._get_shard(channel)
>         await shard.subscribe(channel)
> ```
> 
> That is, if `receive()` is called with a channel name it doesn't expect, it can subscribe to that channel on-demand and continue on its way. That _should_ work fine.
> 
> I don't have any spare cycles right now. Can you experiment with this idea and post back here if it solves your problem? If so, we can look at doing a PR to fix this.

I tried this, but it seems like this is not enough. It _seems_ that messages are not being received. I'm still trying to debug what the issue is.
