### ISSUE TITLE
Channel Redis with sentinels

### ISSUE THREAD

**Issue by Patrickhhh99** [django/channels_redis#283]
Is there any code example of how to connect to Redis sentinel in Django Channels?
I am current using this way to connection but it is not working.

```
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                ("10.16.11.xx1", 26379),("10.16.11.xx2", 26379),("10.16.11.xx3", 26379)
            ],
            "master_name": "mymaster"
        },
    },
}
```

**Comment by acu192** [comment]
The only docs I know of are [this section of the README](https://github.com/django/channels_redis#hosts). Maybe @qeternity can chime in if he knows of an example.

**Comment by qeternity** [comment]
The docs are a bit contradictory, but it's actually the vanilla redis which is misleading (although helped because there is sample code). The `hosts` key should be `sentinels` since we just expand the config dict.

A one liner could also allow passing in `hosts` but not sure that's the best approach because redis hosts are distinct from sentinel hosts.

**Comment by Patrickhhh99** [comment]
Thanks for you reply! I changed the `hosts` key to `sentinels` but it is showing unexpected keyword error.

```
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/channels/layers.py", line 74, in _make_backend
Performing system checks...

    return backend_class(**config)
TypeError: __init__() got an unexpected keyword argument 'sentinels'

```

**Comment by qeternity** [comment]
Sorry - haven't looked at this code in ages. My mistake: the hosts key should be a dict with sentinels and master_name keys. Here is from our prod code:

![image](https://user-images.githubusercontent.com/33002121/145448053-8ca37523-80b0-4076-9fab-3926b920cfe8.png)

**Comment by Patrickhhh99** [comment]
Thank you so much!
