### ISSUE TITLE
ERROR: Failed building wheel for hiredis

### ISSUE THREAD

**Issue by ma2-b** [django/channels_redis#309]
When I training to download the package It gave me this error:

  Building wheel for hiredis (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      C:\Users\Pc\AppData\Local\Temp\pip-install-ygi77b2k\hiredis_a49152a1258b4020a9310d77dd47836b\setup.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
        import sys, imp, os, glob, io
      C:\Users\Pc\Desktop\chat_app\lib\site-packages\setuptools\dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\hiredis
      copying hiredis\version.py -> build\lib.win-amd64-cpython-310\hiredis
      copying hiredis\__init__.py -> build\lib.win-amd64-cpython-310\hiredis
      copying hiredis\hiredis.pyi -> build\lib.win-amd64-cpython-310\hiredis
      copying hiredis\py.typed -> build\lib.win-amd64-cpython-310\hiredis
      running build_ext
      building 'hiredis.hiredis' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hiredis
  Running setup.py clean for hiredis
Failed to build hiredis
Installing collected packages: hiredis, aioredis, channels-redis
  Running setup.py install for hiredis ... error
  error: subprocess-exited-with-error

  × Running setup.py install for hiredis did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      C:\Users\Pc\AppData\Local\Temp\pip-install-ygi77b2k\hiredis_a49152a1258b4020a9310d77dd47836b\setup.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
        import sys, imp, os, glob, io
      C:\Users\Pc\Desktop\chat_app\lib\site-packages\setuptools\dist.py:772: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running install
      C:\Users\Pc\Desktop\chat_app\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\hiredis
      copying hiredis\version.py -> build\lib.win-amd64-cpython-310\hiredis
      copying hiredis\__init__.py -> build\lib.win-amd64-cpython-310\hiredis
      copying hiredis\hiredis.pyi -> build\lib.win-amd64-cpython-310\hiredis
      copying hiredis\py.typed -> build\lib.win-amd64-cpython-310\hiredis
      running build_ext
      building 'hiredis.hiredis' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> hiredis

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by carltongibson** [comment]
This is the key bit:

```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
```
