### ISSUE TITLE
Redis dependency discrepancy 

### ISSUE THREAD

**Issue by marksweb** [django/channels_redis#350]
I'm in the process of upgrading a project to django 4.2 and all things channels v4 and I've got web sockets failing so I'm going back to basics to verify the project setup.

Going over the readme I can see a requirement of `Redis >= 5.0` (this version changed in 2020 [here](https://github.com/django/channels_redis/commit/5ddd906efdcae55fc5c3a356a0408acb3c63afdd)), but `pip-tools` was happy with me still using `redis==4.5.1` so I dug a little deeper.

In the installation requirements for v4 and the actual requirement is at `redis>=4.2.0` ([see here](https://github.com/django/channels_redis/blob/95d87449c2b899c1cfdf8a10cfa1425e30127ef2/setup.py#L33)). 

I assume therefore that redis 4 is still ok to use, but this may confuse anyone going through this same process as me.

**Comment by carltongibson** [comment]
It means Redis itself not redis-py

**Comment by carltongibson** [comment]
> I've got web sockets failing 

If you can reduce these to something here, happy to take a look — It's 100% not clear yet that either `redis-py`'s new async stuff baked, or that we're wrapping it just right, so there could well be issues.

**Comment by marksweb** [comment]
> It means Redis itself not redis-py. It was updated when we used some commands introduced in Redis 5.
> 
> There is no redis-py 5.

Yes, confusion on my part with you mentioning "redis-py" because of the package [py-redis](https://pypi.org/project/py-redis/) and too many days looking at pypi & packages as part of this upgrade job also likely playing a part.

**Comment by carltongibson** [comment]
Cheer Mark. Yes, likely I'm getting it backwards. 
🤯

I'm going to have to invoke the _You know what he means_ school. 😝
