### ISSUE TITLE
Missing tag for 4.2.0 release

### ISSUE THREAD

**Issue by doge-tech** [django/channels_redis#392]
Hi,

It looks like version 4.2.0 of channels_redis has been released on PyPI but there's no corresponding tag in this GitHub repo. I'm trying to update the channels_redis package in Debian, but the missing tag is an issue because these tags are used as a source of truth for the reproducibility of Debian package builds.

While I could work around this by using the release tarballs on PyPI for the Debian package, these tarballs don't include the pytest tests, which are a key metric for determining the success of a package build.

Could you please tag the commit used to generate the 4.2.0 release (I assume it's [this one](https://github.com/django/channels_redis/commit/594831714df69657af75cac4fafecb0d6812d6dc)) or issue a new release with a corresponding tag?

Many thanks!

**Comment by carltongibson** [comment]
Yep, good spot thanks. Tagged and pushed.
