### ISSUE TITLE
RedisLocalChannelLayer ipc layer configuration

### ISSUE THREAD

**Issue by soulhunter1987** [django/channels_redis#47]
There is no possibility to pass "message_memory" and "group_memory" settings to internally used ipc layer when using RedisLocalChannelLayer

**Comment by andrewgodwin** [comment]
You're very right, there is not - it's probably the case that the local layer should take a dict to pass down to the IPC layer for its config.

**Comment by andrewgodwin** [comment]
LocalLayer is now gone as of version 2.0, so closing.
