### ISSUE TITLE
Support for redis slave connections

### ISSUE THREAD

**Issue by jshuping** [django/channels_redis#57]
The sentinel-based channel can give you a handle to the current redis master (`_master_for()`)
We would like a way to retrieve and connect to the slaves as well for certain lower-priority things
such as our solution to issue #54.  A `_slaves_for()` would be nice!

**Comment by b-thebest** [comment]
Hello, Can I work on this issue? I have 1+year of experience of working with python and I want to cmontribute open source projects

**Comment by carltongibson** [comment]
Hi @b-thebest yes, please do. You’re very welcome!

**Comment by b-thebest** [comment]
Hi @carltongibson, Could you please explain me this issue in more details please. As I am new to open sourcel, I have less experience of contributions. 
Thank you

**Comment by carltongibson** [comment]
Sentinel support was part of v3.3.0
