### ISSUE TITLE
python2.7 and python3 working hand in hand

### ISSUE THREAD

**Issue by ajakubo1** [django/channels_redis#64]
So...

Quite recently I've started moving from python2.7 env to a python3.6. We've re-written the code, everything was working properly and the only thing to do is to put the project on prod and battle-test it.

So I spawned a server, deployed the upgraded app, connected everything to production db and production redis server. And everything seemed to work properly. But there was a problem. There was quite a lot of 502 errors from channels connector. A lot of reconnects. From what I saw, about 25% of websocket connections to that server was failing (I based it on my own experiences, but nginx logs pretty much confirmed it). There was unnaturally more errors on python3 server then on python2.7 server.

When I did manual testing - it turned out, that I had those errors when I refreshed the web page. So basically - I was having trouble establishing the initial connection. I didn't found any problems with websockets when that connection has been established.

So at first I checked the code - but I actually didn't change anything for websocket-serving part. Well, I did have some code for reformatting byte stream into a unicode, but nothing more.

I checked the behavior of ``daphne`` and ``runworker`` - it seemed to me, that daphne received messages for my requests, but workers didn't receive it at all. I even tried running those commands in debug manually. This shown to me, that ``runworker`` command didn't receive connect/disconnect messages sometimes.

This seemed weird to me, as I couldn't replicate that situation in my local environment. I had always 100% success rate in python3 env for connecting.

So today, I've tried spawning another local server, with python2.7 environment and connecting it to my redis db, which I use in python3.6 environment. And to my astonishment - the sheer fact that I connected to redis with python2.7 env (without any traffic), broke python3.6 connection flow.

When I disconnect (disable both daphne and webworkers on python2.7 env) - I'm not having problems connecting to my python3.6 instance.

But as soon as the connection is made from python2.7 servers - it seems to break everything for python3.6 servers.

In the same time - python2.7 servers seem to be unaffected at all.

Has anyone encountered such problems before? I'm actually not sure where the problem is - is it in asgi_redis layer, or somewhere else. Just opening an issue to ask around and let the community know that there might be problems with connecting python2.7 and python3.6 apps in one redis instance.

asgi_redis version I'm using: ``1.4.2``

Let me know if you need anything else.

**Comment by ajakubo1** [comment]
OK - I've just checked - I can leave daphne running on python2.7 server, the problem seems to occur when workers are started.

**Comment by andrewgodwin** [comment]
I'm not aware of any potential for incompatibility between different Python versions - they only exchange JSON, after all. I'll leave this open in case more evidence comes to light, but it'll probably get closed once we jump asgi_redis up to version 2.0 and Python 3 only.

**Comment by ajakubo1** [comment]
Yep, I'm OK with that.

Actually - I'm not very acquainted with docker, but I will try to replicate the whole thing in a smaller environment with some sample code. This way I'll make sure that the problem is not related to my app.

I'm actually not even sure if the potential problem is in ``asgi_redis``, or in some other lib...

**Comment by ajakubo1** [comment]
Oh yeah - and btw. The problem is not with sent messages.

It seems to be in the connection layer itself.

I currently have:
- First vagrant box with redis and my app in python3.6
- Second vagrant box with my app in python2.7

That python2.7 vagrant box is connecting to redis located in python3.6 vagrant box. I only reach python3.6 vagrant box with my browser. When I disable ``runworker`` command on python2.7 box, I don't have any problems with connecting to python3.6 box websockets. Problem starts, when I enable ``runworker`` on python2.7 box. At that moment, some of my connection attempts with python3.6 box end in 502 errors. As soon as I disable the ``runworker`` once again - everything works perfectly.

**Comment by ajakubo1** [comment]
OK, so I just managed to replicate the problem working on your repo, @andrewgodwin:

https://github.com/ajakubo1/channels-examples

1. what I did here is - I only opened redis ports in docker, so that I can access it from my local machine.
2. I tried out ``databinding`` app, ran all of the commands to setup docker box (added some sliders), and I made sure everything worked properly according to your scenario (so - a couple of browsers open, slide the slider) - I didn't noticed any problems at all
3. (again - not a docker guy - sorry :D) - from my local machine (which is ubuntu 16.04), I've created 2 virtualenvs: ``gremlin`` - with python2.7 installed, and ``gremlin-3`` with python3.5 installed.
4. I installed requirements from databinding requirements files for both ``gremlin`` and ``gremlin-3``
5. Just to make sure everything is working for python3.5, I've used sourced ``gremlin-3``, and ran:

```python manage.py runserver 8001```

from databinding folder.

Remember - I still have that docker image running, so I can access original app on port 8000, and also connect to redis server which is used there. Plus - I'm serving the data from ``sqlite`` file.

6. Accessed 8001 port with a couple of tabs, move the sliders around, made sure everything is working properly, refreshed the page on port 8000 to make sure I can connect to websocket all the time
7. Canceled that 8001 port instance
8. Sourced ``gremlin`` and ran the server in exactly the same manner as I did with ``gremlin-3``:

```python manage.py runserver 8001```

9.  Accessed 8001 port with a couple of tabs, move the sliders around, made sure everything is working properly for both 8000 and 8001 instances
10. Tried refreshing a couple of times... And... This happened:

![image](https://user-images.githubusercontent.com/8577405/32375401-bdad6e9e-c0a1-11e7-93e4-df476086863a.png)

Connection failed. That's actually the original problem I had - I just reconfigured ``WebsocketBridge`` in my application so it wouldn't cancel the connection on it's own, but I increased the timeout values (this then triggered 502 errors for me).

On firefox:

![image](https://user-images.githubusercontent.com/8577405/32375556-5d8e063a-c0a2-11e7-9ed4-8d5a335db21f.png)

![image](https://user-images.githubusercontent.com/8577405/32375581-6b439c54-c0a2-11e7-9fbf-d4f9fe9c0f91.png)

Just like my symptoms - about 20-25% of connections have to be re-established.

**Comment by andrewgodwin** [comment]
OK, so in that case it's just general layer failure, like https://github.com/django/asgi_redis/issues/62 but maybe different. I'll try and look at it soon but I don't have a lot of spare time at the moment.

**Comment by andrewgodwin** [comment]
Closing as we've entirely rewritten the layer to be asyncio-based and get rid of most connection failures.
