### ISSUE TITLE
Hitting redis connection limit (10,000 connections)

### ISSUE THREAD

**Issue by beaugunderson** [django/channels_redis#75]
Reported this on IRC and @andrewgodwin suggested I log a message here; he thought it might be related to connection pools.

It takes 30-90 minutes for us to hit this in production.

**Comment by andrewgodwin** [comment]
I also have this weird feeling that https://github.com/django/channels_redis/issues/74 is related to this. I might just try and make `channels_redis` close connections and reopen them every time rather than trying to use a connection pool, as I'm not sure the efficiency gains are worth it.

**Comment by andrewgodwin** [comment]
I've overhauled the connection backend to not use pooling and be a lot simpler - it means a millisecond or more per call but the tradeoff is worth it here I think. It's available in https://github.com/django/channels_redis/commit/6613baf73a8fbb2a01e08008160a19f27981ef25 - I can't detect leaks locally now, but if you could try it out and see if it works under load that would be great (and then I can release it)

**Comment by beaugunderson** [comment]
@andrewgodwin will try momentarily!

**Comment by beaugunderson** [comment]
@andrewgodwin seeing this on that commit:

```
2018-02-21 05:12:49,869 ERROR    Exception inside application: Task <Task pending coro=<RedisChannelLayer.receive_loop() running at /app/src/channels-redis/channels_redis/core.py:185>> got Future <Future pending> attached to a different loop
  File "/usr/local/lib/python3.6/site-packages/channels/consumer.py", line 54, in __call__
    await await_many_dispatch([receive, self.channel_receive], self.dispatch)
  File "/usr/local/lib/python3.6/site-packages/channels/utils.py", line 47, in await_many_dispatch
    result = task.result()
  File "/app/src/channels-redis/channels_redis/core.py", line 166, in receive
    task.result()
  File "/app/src/channels-redis/channels_redis/core.py", line 185, in receive_loop
    async with self.receive_lock:
  File "/usr/local/lib/python3.6/asyncio/locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "/usr/local/lib/python3.6/asyncio/locks.py", line 176, in acquire
    yield from fut
  Task <Task pending coro=<RedisChannelLayer.receive_loop() running at /app/src/channels-redis/channels_redis/core.py:185>> got Future <Future pending> attached to a different loop
```

**Comment by beaugunderson** [comment]
@andrewgodwin will update to latest `asgiref` and see and see if that changes anything

**Comment by andrewgodwin** [comment]
Ooh, yes, I think that's a problem in my commit. Let me fix that.

**Comment by beaugunderson** [comment]
@andrewgodwin awesome, thanks! (by `asgiref` above I guess I meant `aioredis`, that's the only one that's out of date)

**Comment by andrewgodwin** [comment]
Yeah, this is because I introduced a lock that will persist across loops. I can fix that.

**Comment by beaugunderson** [comment]
😍

**Comment by andrewgodwin** [comment]
It's weird that it happens actually - all the `receive` calls should be happening in one outer loop - but I should fix it anyway. While I do, are you just running a standard Daphne?

**Comment by beaugunderson** [comment]
@andrewgodwin yup:

```sh
daphne app.asgi:application --bind 0.0.0.0 --port "$PORT"
```

where `app/asgi.py` is:

```python
import os
import django

from channels.routing import get_default_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'app.settings')

django.setup()

application = get_default_application()
```

**Comment by beaugunderson** [comment]
I also have a Django management command running in cron that looks like:

utilities.py:

```
sync_group_send = async_to_sync(channel_layer.group_send)

```

process_reminders.py:

```
from .utilities import sync_group_send

sync_group_send('some_group', {...})
```

**Comment by andrewgodwin** [comment]
Hm, weird. I've made a test that replicates your error now anyway, so I'll worry about how receives happen in two threads later :)

**Comment by andrewgodwin** [comment]
OK, this is going to take a bit longer than expected, so it'll be tomorrow or later in the week before I can fix it!

**Comment by beaugunderson** [comment]
understood--will stand by :)

**Comment by beaugunderson** [comment]
One more quick data point--eventually the exceptions just stopped happening (I've been tailing the logs) and connections started going through normally. Mystifying!

**Comment by andrewgodwin** [comment]
If there is one phrase I can use to describe asynchronous programming from the outside it is indeed "mystifying"!

Anyway, I think I might have this solved locally, or at least have a better error that if you trigger it means there's a bug in Channels 2. Just have to get the tests done and then I'll push up a commit.

**Comment by andrewgodwin** [comment]
OK, I have pushed up a new commit that should handle multiple event loops better: https://github.com/django/channels_redis/commit/d69d722bfa9bd01a715a9f56ff6bc6bd7a2a3d13

**Comment by beaugunderson** [comment]
@andrewgodwin working great so far, no errors/warnings of any kind!

**Comment by andrewgodwin** [comment]
Alright, other people have reported no errors too so I'm going to close this and roll a release. Thanks for your help testing!
