### ISSUE TITLE
Problems with maintaining open websocket connections and sending group messages

### ISSUE THREAD

**Issue by ploggingdev** [django/channels_redis#79]
After upgrading from channels-redis 2.0.3 to 2.1.0 I noticed that users that connect to my chat room site frequently see dropped group messages and have trouble maintaining open websocket connections. Usually even if a user disconnects from the server, the reconnecting websocket code takes care of opening another connection and it used to work fine before the upgrade. I'm not able to reliably reproduce the bug since it happens randomly and there are no exceptions raised. It usually occurs after a websocket connection has been open for a few minutes. Group message delivery is very unreliable after the upgrade. Could it be related to moving away from connection pools and instead opening and closing connections every time? Unfortunately I don't have a reliable way of reproducing the bug and no relevant traceback or logs to share. Anyone else facing this issue after the upgrade?

Edit : it looks like there's no issue maintaining an open websocket connection. After a few minutes I am able to send messages and they get saved to the database, but sending group messages from the consumer does not work.

**Comment by andrewgodwin** [comment]
I'm not exactly sure what you are describing - specifically, I need to have it simplified into:

* What you think should happen
* What actually happens
* How I can reproduce it

Without those I'm afraid there's not much I can do.

**Comment by ploggingdev** [comment]
> What you think should happen

Once I open a websocket connection and idle for a few minutes, I should still be able to receive group messages sent from consumers.

> What actually happens

After idling for a few minutes, users are able to send websocket messages but don't receive group messages.

> How I can reproduce it

Run the multichat project and leave it open for a few minutes and then send a message. The message gets saved to the database but the group message won't be delivered to users who have been idling for a few minutes. This happens fairly randomly, so it's not a very reliable way of reproducing the bug.

**Comment by andrewgodwin** [comment]
Alright, that's a bit clearer. I won't be able to look at it myself for a bit, so if you want to poke around in Redis and see what's happening, or try different scenarios (does it happen if you send a lot of messages in the middle? if you send no messages? etc.) that would help.

**Comment by ploggingdev** [comment]
Take your time! I will try and understand what's happening and hopefully will have something useful to share.

**Comment by zahlio** [comment]
We are also having this issue. Groups works for a couple of minutes and then it stops working, websocket connection is still active.

**Comment by andrewgodwin** [comment]
@zahlio If you can also work out what scenarios it happens in (exact length of time, failure rate, conditions) that would help

**Comment by sgryco** [comment]
@andrewgodwin @zahlio I think we are facing the same issue, with the 2.1.0, not present in the 2.0.3.
I'm a bit new to Django/Channels, but I have an old background in networks.
Here is what I have understood so far, and what tracks I have followed to find the problem.
Situation:
We want to develop a real-time web app, monitoring values. 
We have set-up a celery periodic task that retrieves data and then send a message to a group using channels. We use redis-server as the backend and have the last version of all the python django package (we tested with pip and directly from the git latest commit). We run everything (redis & daphne) inside a docker container.
To be sure the problem doesn't come from celery, we use rabbitmq for celery.

Test case to reproduce the bug (not very deterministic, but high probability): 

1. Create a celery task that run this code every 1 seconds (PERIOD).
`nmsg=10    
for i in range(nmsg):
        a = random.randint(1, 100)
        async_to_sync(channel_layer.group_send)(
            "bike_group", {
                "type": "group.send",
                "text": "VALUE=" + str(a)}
        )`
2. Open 2-5 browsers that connect to the channel. We can also reproduce the bug by using the python `websocket-client`:
`wsdump.py ws://localhost:8000/ws/ -vv`

The number of connections in the state TIME_WAIT quickly rises, (visualised with `netstat -at`). 
Here is the number of sockets in the TIMEWAIT state with nmsg=1:
-When the socket connection is established: 2
-When I send 20 socket pings from the client to the server: 2
-When the periodic task, sending 1 group message to one client: around 180 per message sent, after 5-10 messages: around 950

With nmsg=10 and PERIOD=1, the number of connection in TIME_WAIT state can rises in proportion to the number of clients connected. With around 50 clients, the number of connection reaches 28k and lead to the following error:
`OSError: [Errno 99] Cannot assign requested address`

The bug:
Without any specific values of clients, but usually more than 5, the server stops sending messages. The redis key for the clients continue to be filled, but the task suppose to retrieve them seems to be blocked. The daphne log shows no error even in -v3. This bug happens **before** the number of connection saturates, I don't know if it is related of not.

The only solution is to restart the daphne server.
 
Let me know if I can provide more detail on how to reproduce the bug.
In any case, thank you for the development of Channels.
Best Regards

**Comment by tobyspark** [comment]
For what it's worth, I had an issue with multiple websockets and group messages that turned out to be a symptom of running python 3.5.2 instead of 3.6.4. Group messages from a worker task were stopping being received by a websocket consumer shortly after a second websocket connection. One debugging step that helped and I don't see mentioned here is `redis-cli monitor`, which established that the messages were being _sent_ at least.

If, as I was, you're running the stock Ubuntu 16.04 LTS python, then upgrade and verify your provisioning uses `pip3.6` and `runworker` uses `/usr/local/bin/python3.6`,  etc.

**Comment by mmcardle** [comment]
Also hitting this issue
upgrading from python `3.6.1` to `3.6.4` seems to have addressed the issue.

Notes: Wrote a small script to monitor groups and the messages in each channel and noticed that some channels where filling to capacity (100), this was with 3 browser consumers

```
import time
from channels.layers import get_channel_layer

channel_layer = get_channel_layer()

while True:
    for group in ['group1', 'group2']:
        print('GROUP', group)
        for channel, length in AsyncToSync(channel_layer.group_length)(group).items():
            print(channel, length, '*' * length)
        print('#####')
    time.sleep(2)
```

```
#####
GROUP group1
specific.hjnjHoSL! 86 **************************************************************************************
specific.esJeWTdh! 100 ****************************************************************************************************
specific.SIQdBwsF! 100 ****************************************************************************************************
specific.CWoEUKrs! 100 ****************************************************************************************************
specific.gvbgtFfG! 100 ****************************************************************************************************
specific.xaTlLbhi! 100 ****************************************************************************************************
specific.lrJbpbKc! 22 **********************
specific.KnipHWzI! 100 ****************************************************************************************************
specific.gkVzwKzT! 100 ****************************************************************************************************
specific.DpKdnEGy! 0
#####
...
```

**Comment by nikssardana** [comment]
I am having a similar problem.

I am using Django 1.9.3 with channels version 0.9.3. The `CHANNEL_LAYERS` backend I am using is `asgi_redis.RedisChannelLayer`.

To keep an "always on" connection, I have implemented my own ping-pong mechanism on client side using nodejs.
The client side script sends a "ping" message to django channels at regular intervals, which replies with a "pong" message.
For some seconds, the group messages are also received on client side.
But after some time, the Group messages are not received, though the pong messages sent via `message.reply_channel` are working fine. 

Please help.

**Comment by shuayb** [comment]
I followed the tutorial mentioned in the documents. Whenever I opened multiple browsers and sent messages for a while it would be fine but later, the messages would drop. Redis received the messages though. 

This was in the logs when the messages droped, it was repeated multiple times:
`Creating tcp connection to ('127.0.0.1', 6379)`

Thinking its a redis issue I tried to use a unix socket connected as mentioned [here](https://github.com/django/channels_redis/issues/18) and increased value of  _/proc/sys/net/core/somaxconn_. That didn't help. 

Creating new virtualenv with python 3.6.4 solved the problem, I used 3.5.2 before. I am not sure if this is a permanent fix.

**Comment by andrewgodwin** [comment]
Hm. Upgrading from Python 3.5 to 3.6 is certainly a common narrative for the fixes for this kind of issue, but I don't know what root issue would be doing that.

**Comment by andrewgodwin** [comment]
I suspect this will have been fixed along with #86 in the new 2.1.1 release. I'd appreciate if someone in the thread could verify that.

**Comment by sgryco** [comment]
Hello Andrew,
I have tested version 2.1.1, and I was not able to reproduce the "freeze bug". Thank you!
On the other hand, the number of connections used is still much more important than before.
Sending 10 messages to a group of 20 users every second for 30 seconds can reach the 28k connection and run out of ports, which will disconnect all the clients.
Let me know if a sample Django project would help you on this part, or if you require any other information.

**Comment by andrewgodwin** [comment]
@sgryco Where are you running your code? I haven't been able to reproduce the Redis connection problem locally but it varies a lot by environment.

**Comment by sgryco** [comment]
@andrewgodwin I have created a simple project that can reproduce the bug.
It runs in docker, with celery.
You can get it here, I have tried to make it as light as possible.
https://github.com/sgryco/socketSpammer
Opening 20 clients to localhost:8000 will produce around 20k+ connections (closed but still in the TIME_WAIT state)
You can also monitor the number of connections just for one client.
The commands are provided in the readme. Let me know if anything needs precision.

**Comment by andrewgodwin** [comment]
OK - I'll see if I can take a look in the next few weeks.

**Comment by abrown1982** [comment]
I'm aware this issue is closed but it took me over a day of tracing through the code to identify this was the issue we were having with sockets randomly stopping sending new messages.  Can I suggest that the docs should be updated to mention that Python 3.6 should be used, not python 3.5.2?

**Comment by rohitsharma1113** [comment]
I am still facing this issue where I am unable to receive any group_send messages in the socket on the front end after sometime (~10secs) even though the connection is alive. 
I am using 8 daphene servers and every socket typically receives 25-30 messages per 10 seconds. 
channels-redis version being used in 2.2.1 with python 3.6.5 but I believe the issue was resolved post 2.1.1. Any help here would be appreciated.

**Comment by m4rk3r** [comment]
I'm also encountering this issue.. @rohitsharma1113 did you ever solve it? @andrewgodwin have any hints what this might be?

I'm noticing (particularly with localhost development & frequent server reloading) when a socket hangs up before disconnecting it doesn't get cleaned up. Imagine cleanup will eventually happen w/ `group_expiry` and tweaking that might provide some relief. But until it's cleaned up, for some reason, dispatching messages to multiple groups that have some zombies takes an inordinate amount of time.. the weird thing though is that it's only takes a long time for the second group, the first group is always dispatched quickly..

I notice that the more these zombie clients that back up in a group, the slower it takes to dispatch messages to active clients in that group. Example:

I have two groups, main & admin. admin has one active and 4 zombies.
```
127.0.0.1:6379> zrange asgi:group:chat_admin 0 -1
1) "specific.7093984cf630465685d3b280354d1d5c!d575c2fee8d248f5bce5d218419e684c"
2) "specific.b47cab70e906447297dd81479859127a!9445ea46518348edbb6bb9700d09f8f9"
3) "specific.4002233c2bec4652bb50983f5fc03c77!bbf9c85b4d6d4636bb18d461600b3dd8"
4) "specific.888ba629538f42b98a0a24faff90fbe4!665aedfc972c47648b6bcd9fd2e63f1a"
5) "specific.86c5dca354604a8289c7f41309d52c5f!7a7c8242496e4b698455da33137fd98c"
```
code to dispatch messages to both groups:
```
    async def broadcast_message(self, data):
        for gp in self.groups:
            print('sending to ',f'chat_{gp}', data)
            t = time.time()
            await self.channel_layer.group_send(
                f'chat_{gp}',
                {
                    'type': 'broadcast',
                    'data': data
                }
            )
            print(f'sent in {time.time() - t} seconds')
```
output:
```
received {'type': 'chat', 'message': 'hello'}
sending to  chat_main {'type': 'receipt', 'messageData': {'message': 'hello', 'id': 'f733a55c-f203-11ea-8feb-0711cb1fb469', 'user': 'joe'}}
sent in 0.0044269561767578125 seconds
sending to  chat_admin {'type': 'receipt', 'messageData': {'message': 'hello', 'id': 'f733a55c-f203-11ea-8feb-0711cb1fb469', 'user': 'joe'}}
sent in 10.191818475723267 seconds
```

Now if I swap the order that groups are sent and send the `main` group second (which has even more zombie clients ~70 currently) the delay is even more pronounced:
```
received {'type': 'chat', 'message': 'test2'}
sending to  chat_admin {'type': 'receipt', 'messageData': {'message': 'test2', 'id': 'aaf101ca-f204-11ea-8feb-0711cb1fb469', 'user': 'joe'}}
sent in 0.002611875534057617 seconds
sending to  chat_main {'type': 'receipt', 'messageData': {'message': 'test2', 'id': 'aaf101ca-f204-11ea-8feb-0711cb1fb469', 'user': 'joe'}}
sent in 35.346376180648804 seconds
```
Should I be doing more to cleanup `power failure` type disconnections or is there something else contributing to this delay?

**Comment by carltongibson** [comment]
Hi @m4rk3r I think it would be best if you open a fresh issue here. (It's not clear that the issue is the same or not...)
