### ISSUE TITLE
Support Redis Sentinel

### ISSUE THREAD

**Issue by ilavender** [django/channels_redis#80]
maybe I'm missing something but I cannot see how to configure channels_redis.core.RedisChannelLayer to use redis sentinel.
Is that even supported?

**Comment by andrewgodwin** [comment]
It's not - I had to remove the support in the move to the `aioredis` library, as it has a different sentinel interface. I'll transform this into a feature request for it.

**Comment by vanzi** [comment]
@andrewgodwin What's the expected scope of this feature here? I had to implement something minimal that allows us to connect channels to a Redis cluster, but I'm not sure if it's worth merging it back here without proper auto-reconnect support (which was not needed for our case).

**Comment by andrewgodwin** [comment]
The idea is that you can supply a Sentinel and the name of the master inside the sentinel to use for each shard, and that it would correctly auto-reconnect to get new sentinel information and switch if appropriate.

**Comment by vanzi** [comment]
@andrewgodwin What I was actually wondering about would probably be more accurately described as an auto-retry. That is in all the layer methods that make use of the `async with self.connection` context manager, should there be a logic to keep retrying until the switch actually happens (that takes a few seconds)?

Feel free to have a look at my current implementation in https://github.com/PiwikPRO/channels_redis/pull/1. The goal for us was a) to connect to Redis through a Sentinel, and b) to have the application continue working after a master switch (but it is okay to disconnect the websockets in the process).

**Comment by rakyi** [comment]
Is there any progress on this? Would you be interested in a PR?

**Comment by carltongibson** [comment]
@rakyi: Yes. 😀 Status: limited-time. So user-driven input is super welcome.

If you'd like to open a PR early, for feedback, please do.

**Comment by severindellsperger** [comment]
@andrewgodwin @carltongibson 
Is there any news from maintainer's side? It looks like @rakyi has brought up some conclusion here.
I think this would be very useful for a bunch of people.
Anyway, is there any workaround here?

**Comment by qeternity** [comment]
This has since been implemented.

**Comment by carltongibson** [comment]
Yep. Release coming in this week
