### ISSUE TITLE
No support for username, password, or other keyword arguments to aioredis.create_redis

### ISSUE THREAD

**Issue by djarb** [django/channels_redis#82]
https://github.com/django/channels_redis/blob/f1580fcc3d5b1e28be9ba03e8a38fc57c68bed8c/channels_redis/core.py#L70

This could be fixed simplistically by changing line 86 to the following:

} if not isinstance(entry, dict) else entry)

**Comment by andrewgodwin** [comment]
Redis does not have username support. You should be able to add a password using the URI format with `redis://:password@hostname/`.
