### ISSUE TITLE
channels_redis/core.py Bad default hosts value

### ISSUE THREAD

**Issue by jvhjvh** [django/channels_redis#84]
Minor thing that I ran across trying Channels 2 out. The default hosts value is not an array in decode_hosts(), yet is expected to be an array in connect(). This is in channels_redis/core.py 2.1.0.

**Comment by andrewgodwin** [comment]
Can you be more precise about what files you're referring to? There is no `decode_hosts` function in the codebase.

**Comment by jvhjvh** [comment]
Hi, this is the repository channels_redis in function decode_hosts(), file channels_redis/core.py, line #77, master branch Feb 21, 2018 version, accessible as 
https://github.com/django/channels_redis/blob/master/channels_redis/core.py
Probably should have some brackets around the braces but I don't know the code much at all so I would rather leave the fix to you. Sorry for no pull request in any case. Hopefully this helps.

**Comment by andrewgodwin** [comment]
Yup, I see it - I'll fix it. In future, you can open issues like this against the `channels_redis` repository itself!
