### ISSUE TITLE
group_send drops messages as of 2.1.0

### ISSUE THREAD

**Issue by gravitylow** [django/channels_redis#86]
Since the changes to the receive loop in 6613baf7 group messages are occasionally dropped to one or more channel layers, and eventually stops sending messages altogether. I cannot reproduce this issue with 2.0.3.

I know this isn't particularly helpful because of its vagueness but it is reproducible using the provided multichat project. Setup is 3 connected clients with one sending numbered messages.

Screenshot of listener 1: https://i.imgur.com/KDAKXuO.png
Screenshot of listener 2 with dropped messages: https://i.imgur.com/CFWPifi.png

When changing requirements to use 2.0.3, this issue goes away. While debugging this I discovered that, at some point, the ```receive_loop``` stops running and misses the messages that have been pushed to redis. I have not yet been able to determine why this is.

**Comment by andrewgodwin** [comment]
What Python version are you using?

**Comment by gravitylow** [comment]
Hmm... I thought it was 3.6 but it was 2.7. Just ran on 3.6 and haven't seen the issue yet. Is there a known incompatibility?

**Comment by andrewgodwin** [comment]
Uh, the code should not even be able to run on 2.7, so if you were doing that I would be very impressed. I have heard reports of a 3.5 -> 3.6 upgrade fixing a very similar issue, however.

**Comment by gravitylow** [comment]
I would have expected it to fail hard too so I didn't check. Thanks for the help and the great work on the lib, very much appreciated.

**Comment by gravitylow** [comment]
After looking into this more, I think I was right the first time that this is a valid bug on python 3.6. I realized that on my test above where I said I hadn't seen the issue after upgrading python, I was still running the 2.0.3 version. Moving that to 2.1.0 does make the problem crop up again.

To double check I used your docker file to host the server (which should only have 3.6 installed) and it does have the same issue. If you have a chance, try running it locally as well and seeing if you can duplicate as in the screenshots. Reverting the changes from 6613baf does seem to consistently fix the issue when its present.

```
$ docker exec -t multichat_web_1 python --version
Python 3.6.4
````

Screenshots:
https://i.imgur.com/LgS7ejP.png
https://i.imgur.com/7etf9Rt.png
https://i.imgur.com/WiGWMiR.png

**Comment by andrewgodwin** [comment]
Ugh, OK. Debugging issues that only happen after a while is the worst. I don't have time to sit down and do a lengthly reproduction of the bug right now, unfortunately - any chance you could work out if it's actually the receive loop dying and/or why it does?

**Comment by gravitylow** [comment]
Yeah I'll continue to take a look and see if I can nail it down. Can't promise a quality PR but I'll get back to you with more info soon.

**Comment by gravitylow** [comment]
@andrewgodwin Upon closer inspection, the issue appears to come from the fact that receive can kill its receive loop after a message is pulled off the buffer ( at [core.py#L173] ), but that receive loop is not guaranteed to be the one who pushed the message onto the buffer (and may be processing a different message at that time).

The result is that messages are occasionally dropped when clients' receive loops are processing messages for a different client. This just depends on which receive loop happens to block first and what stage its at in processing a message if killed, which is why it's not always reproducible.

Example:
1. `receive` function is called for client `asgi.specific!1`, receive loop is started
2. `receive` function is called for client `asgi.specific!2`, receive loop is started
3. `asgi.specific!2` receive loop blocks connection and attempts to pop for general messages
4. `group_send` is called, `send` is called for `asgi.specific!1`
5. message for `asgi.specific!1` is pushed onto `asgi.specific!`
6. message for `asgi.specific!1` is popped by `asgi.specific!2` receive loop
7. message for `asgi.specific!1` is placed onto buffer for `asgi.specific!1` by `asgi.specific!2` receive loop
8. `asgi.specific!1` receive loop blocks connection and attempts to pop for general messages
9. message for `asgi.specific!1` is pulled from the buffer by `asgi.specific!1` receive function
10. message for `asgi.specific!2` is pushed onto `asgi.specific!`
11. message for `asgi.specific!2` is popped by `asgi.specific!1` receive loop
12. message for `asgi.specific!1` is returned by `asgi.specific!1` receive function
13. receive loop for `asgi.specific!1` is finally killed

The final step destroys the message that was in processing by `asgi.specific!1` receive loop

I haven't created a PR because I don't know how you want to deal with this. I think the most pertinent would be to use another mutex to prevent killing loops while they're blocking / popping. I'd be happy to PR if you have a specific direction you want to take.

**Comment by andrewgodwin** [comment]
Thanks for tracing this down. I have half a mind to just remove the process-local stuff for now as it's a massive pain to get right, but the number of redis connections it saves is just too high. Let me see if I can get something in place if you're willing to try it out and report back?

**Comment by andrewgodwin** [comment]
Also, what's curious is that it shouldn't be possible to cancel the receive loop outside of its `await` statement, it's not like there's threading here.

**Comment by andrewgodwin** [comment]
Could you see if the problem is fixed with 9a60fd5? I rewrote the receive loop to be more semaphore-like and just have one instance.

**Comment by gravitylow** [comment]
I have tested using 9a60fd5 and have not seen the issue yet, hopefully it's fixed! Single loop seems like a much more manageable / reliable solution. I'll do more tests on my production implementation that was originally experiencing problems and continue to update you.

**Comment by gravitylow** [comment]
I have not seen the issue appear when doing more extensive testing in my original environment, so I'm going to close the issue. Thank you for your work on this issue and on the project! If you get more reports of this please do not hesitate to reach out to me.

**Comment by andrewgodwin** [comment]
Lovely, I'll put this into a release then. Thanks for the help testing,
