### ISSUE TITLE
channels-redis-2.1.1 downgrades aioredis to version 1.0.0

### ISSUE THREAD

**Issue by kradem** [django/channels_redis#87]
I've had aioredis version 1.1.0 installed but new channels-redis pip upgrade install downgraded it:

    $ pip install channels-redis -U
    Collecting channels-redis
      Using cached channels_redis-2.1.1-py2.py3-none-any.whl
    Collecting aioredis~=1.0.0 (from channels-redis)
      Using cached aioredis-1.0.0-py3-none-any.whl
    Requirement already up-to-date: channels~=2.0 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from channels-redis)
    Requirement already up-to-date: asgiref~=2.1 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from channels-redis)
    Requirement already up-to-date: msgpack~=0.5.0 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from channels-redis)
    Requirement already up-to-date: hiredis in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from aioredis~=1.0.0->channels-redis)
    Requirement already up-to-date: async-timeout in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from aioredis~=1.0.0->channels-redis)
    Requirement already up-to-date: Django>=1.11 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from channels~=2.0->channels-redis)
    Requirement already up-to-date: daphne~=2.0 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from channels~=2.0->channels-redis)
    Requirement already up-to-date: pytz in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from Django>=1.11->channels~=2.0->channels-redis)
    Requirement already up-to-date: twisted>=17.5 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from daphne~=2.0->channels~=2.0->channels-redis)
    Requirement already up-to-date: autobahn>=0.18 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from daphne~=2.0->channels~=2.0->channels-redis)
    Requirement already up-to-date: constantly>=15.1 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from twisted>=17.5->daphne~=2.0->channels~=2.0->channels-redis)
    Requirement already up-to-date: hyperlink>=17.1.1 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from twisted>=17.5->daphne~=2.0->channels~=2.0->channels-redis)
    Requirement already up-to-date: zope.interface>=4.0.2 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from twisted>=17.5->daphne~=2.0->channels~=2.0->channels-redis)
    Requirement already up-to-date: incremental>=16.10.1 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from twisted>=17.5->daphne~=2.0->channels~=2.0->channels-redis)
    Requirement already up-to-date: Automat>=0.3.0 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from twisted>=17.5->daphne~=2.0->channels~=2.0->channels-redis)
    Requirement already up-to-date: txaio>=2.7.0 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from autobahn>=0.18->daphne~=2.0->channels~=2.0->channels-redis)
    Requirement already up-to-date: six>=1.10.0 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from autobahn>=0.18->daphne~=2.0->channels~=2.0->channels-redis)
    Requirement already up-to-date: idna>=2.5 in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from hyperlink>=17.1.1->twisted>=17.5->daphne~=2.0->channels~=2.0->channels-redis)
    Requirement already up-to-date: setuptools in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from zope.interface>=4.0.2->twisted>=17.5->daphne~=2.0->channels~=2.0->channels-redis)
    Requirement already up-to-date: attrs in /home/balnir/.virtualenvs/dev_hm/lib/python3.6/site-packages (from Automat>=0.3.0->twisted>=17.5->daphne~=2.0->channels~=2.0->channels-redis)
    Installing collected packages: aioredis, channels-redis
      Found existing installation: aioredis 1.1.0
        Uninstalling aioredis-1.1.0:
          Successfully uninstalled aioredis-1.1.0
    Successfully installed aioredis-1.0.0 channels-redis-2.1.1

What's this about?

**Comment by andrewgodwin** [comment]
`channels_redis` is version locked to the `1.0` series, as that's all it was tested with. If you want to force-install the new `aioredis` over the top and test that it works I'll unlock the version restriction for the next release,

**Comment by kradem** [comment]
Well all my tests passed with channels-redis-2.1.1 and aioredis-1.1.0 and so I posted here.

**Comment by andrewgodwin** [comment]
I loosened the requirement so it'll allow 1.1 next release.
