### ISSUE TITLE
RedisChannelLayer.send probably ignores specific channels capacity rules

### ISSUE THREAD

**Issue by thomas-riccardi** [django/channels_redis#95]
https://github.com/django/channels_redis/blob/54d935beb6842333ba4f3e6c29cbe86c4307cf16/channels_redis/core.py#L136

At this point the `channel` value is only the non-local part for specific channels (with `!`), but `self.get_capacity(channel)` probably expects the full channel name, doesn't it?

**Comment by andrewgodwin** [comment]
Nah, this is intentional - it doesn't make sense to check the specific channels for rules as their suffix is random, so it only checks up to the potential non-random part (the `!`).

**Comment by thomas-riccardi** [comment]
OK, this issue only made sense if we could properly implement the capacity per channel, which we don't according to #97
