### ISSUE TITLE
group_send could factorize messages destined to the same RedisChannelLayer instance

### ISSUE THREAD

**Issue by thomas-riccardi** [django/channels_redis#98]
Currently each `RedisChannelLayer` instance has its own redis queue, that multiplexes all the asgi channels for this instance.

`group_send` duplicates the message for each member of the group, then for each `RedisChannelLayer` instance redis queue, sends all related messages to this redis queue, with `__asgi_channel__` special key to de-multiplex to the correct asgi channel.

It is inefficient network-wise if multiple members of the group are in fact of the same  `RedisChannelLayer` instance.

This would be a channels_redis network breaking change though...

**Comment by andrewgodwin** [comment]
This is just how the current architecture is designed; I don't want to make the already-complex single-process receiving code even more complex unless someone wants to sit down and write an extremely comprehensive test suite that makes sure there's no concurrency issues.

It's not perfect, but much like Django, the redis channel layer is designed for small to medium size sites - if anyone is going to run a huge site off of the channel layer, they will doubtless have the resources to customise and improve it themselves anyway, and maybe contribute those changes back.
